// 报表模板配置

export interface PrintTemplate {
  key: string;
  name: string;
  code: string;
  description: string;
  dataFields: any[];
  mockData: any;
  fallbackBands: any[];
  fallbackPageSettings: any;
}

export const mockTemplates: PrintTemplate[] = [
  {
    key: 'c_delivery_order',
    name: '物资发货单模板',
    code: 'c_delivery_order',
    description: '用于供应商向医院发送物资时的随货同行单据打印。',
    dataFields: [
      {
        name: 'id',
        label: '发货单号',
        type: 'string',
      },
      {
        name: 'orderId',
        label: '关联订单号',
        type: 'string',
      },
      {
        name: 'supplier',
        label: '供应商',
        type: 'string',
      },
      {
        name: 'sendTime',
        label: '发货时间',
        type: 'string',
      },
      {
        name: 'sendQty',
        label: '总数量',
        type: 'number',
      },
      {
        name: 'totalAmount',
        label: '总金额',
        type: 'currency',
      },
      {
        name: 'creator',
        label: '发货人',
        type: 'string',
      },
      {
        name: 'receiver',
        label: '收货人',
        type: 'string',
      },
      {
        name: 'reviewer',
        label: '审核人',
        type: 'string',
      },
      {
        name: 'remark',
        label: '备注',
        type: 'string',
      },
      {
        name: 'products',
        label: '货物明细',
        type: 'array',
        children: [
          {
            name: 'name',
            label: '产品名称',
            type: 'string',
          },
          {
            name: 'spec',
            label: '规格型号',
            type: 'string',
          },
          {
            name: 'batchNo',
            label: '批号',
            type: 'string',
          },
          {
            name: 'expDate',
            label: '效期',
            type: 'string',
          },
          {
            name: 'unit',
            label: '单位',
            type: 'string',
          },
          {
            name: 'quantity',
            label: '数量',
            type: 'number',
          },
          {
            name: 'price',
            label: '单价',
            type: 'currency',
          },
          {
            name: 'amount',
            label: '金额',
            type: 'currency',
          },
        ],
      },
    ],
    mockData: {
      id: 'DEL-20260605001',
      orderId: 'ORD-20260520092',
      supplier: '国药控股股份有限公司',
      sendTime: '2026-06-05 10:00:00',
      sendQty: 51950,
      totalAmount: 137916,
      creator: '陈志远',
      receiver: '林嘉欣',
      reviewer: '王海波',
      remark: '请核对批号和效期，包含冷链物资需优先入库。',
      products: [
        {
          name: '一次性使用无菌注射器',
          spec: '2ml',
          unit: '支',
          quantity: 300,
          price: 1.5,
          amount: 450,
          batchNo: 'B260601',
          expDate: '2028-06-01',
        },
        {
          name: '生理盐水注射液',
          spec: '250ml',
          unit: '瓶',
          quantity: 160,
          price: 5,
          amount: 800,
          batchNo: 'B260602',
          expDate: '2028-06-02',
        },
        {
          name: '葡萄糖注射液 5%',
          spec: '500ml',
          unit: '瓶',
          quantity: 120,
          price: 6,
          amount: 720,
          batchNo: 'B260603',
          expDate: '2028-06-03',
        },
        {
          name: '医用脱脂纱布块',
          spec: '10cm*10cm 8层',
          unit: '包',
          quantity: 1530,
          price: 3.5,
          amount: 5355,
          batchNo: 'B260501',
          expDate: '2028-05-01',
        },
        {
          name: '一次性医用橡胶检查手套',
          spec: 'M号',
          unit: '盒',
          quantity: 840,
          price: 25,
          amount: 21000,
          batchNo: 'B260502',
          expDate: '2028-05-02',
        },
        {
          name: '一次性使用真空采血管',
          spec: '5ml 促凝管',
          unit: '支',
          quantity: 3050,
          price: 0.8,
          amount: 2440,
          batchNo: 'B260503',
          expDate: '2028-05-03',
        },
        {
          name: '医用外科口罩',
          spec: '非无菌型',
          unit: '只',
          quantity: 10060,
          price: 0.4,
          amount: 4024,
          batchNo: 'B260504',
          expDate: '2028-05-04',
        },
        {
          name: '一次性使用无菌导尿管',
          spec: '16Fr 双腔',
          unit: '根',
          quantity: 570,
          price: 8.5,
          amount: 4845,
          batchNo: 'B260505',
          expDate: '2028-05-05',
        },
        {
          name: '免洗手消毒凝胶',
          spec: '500ml/瓶',
          unit: '瓶',
          quantity: 280,
          price: 18,
          amount: 5040,
          batchNo: 'B260506',
          expDate: '2028-05-06',
        },
        {
          name: '一次性使用无菌注射器',
          spec: '2ml',
          unit: '支',
          quantity: 390,
          price: 1.5,
          amount: 585,
          batchNo: 'B260601',
          expDate: '2028-06-01',
        },
        {
          name: '生理盐水注射液',
          spec: '250ml',
          unit: '瓶',
          quantity: 250,
          price: 5,
          amount: 1250,
          batchNo: 'B260602',
          expDate: '2028-06-02',
        },
        {
          name: '葡萄糖注射液 5%',
          spec: '500ml',
          unit: '瓶',
          quantity: 210,
          price: 6,
          amount: 1260,
          batchNo: 'B260603',
          expDate: '2028-06-03',
        },
        {
          name: '医用脱脂纱布块',
          spec: '10cm*10cm 8层',
          unit: '包',
          quantity: 1620,
          price: 3.5,
          amount: 5670,
          batchNo: 'B260501',
          expDate: '2028-05-01',
        },
        {
          name: '一次性医用橡胶检查手套',
          spec: 'M号',
          unit: '盒',
          quantity: 930,
          price: 25,
          amount: 23250,
          batchNo: 'B260502',
          expDate: '2028-05-02',
        },
        {
          name: '一次性使用真空采血管',
          spec: '5ml 促凝管',
          unit: '支',
          quantity: 3140,
          price: 0.8,
          amount: 2512,
          batchNo: 'B260503',
          expDate: '2028-05-03',
        },
        {
          name: '医用外科口罩',
          spec: '非无菌型',
          unit: '只',
          quantity: 10150,
          price: 0.4,
          amount: 4060,
          batchNo: 'B260504',
          expDate: '2028-05-04',
        },
        {
          name: '一次性使用无菌导尿管',
          spec: '16Fr 双腔',
          unit: '根',
          quantity: 660,
          price: 8.5,
          amount: 5610,
          batchNo: 'B260505',
          expDate: '2028-05-05',
        },
        {
          name: '免洗手消毒凝胶',
          spec: '500ml/瓶',
          unit: '瓶',
          quantity: 370,
          price: 18,
          amount: 6660,
          batchNo: 'B260506',
          expDate: '2028-05-06',
        },
        {
          name: '一次性使用无菌注射器',
          spec: '2ml',
          unit: '支',
          quantity: 480,
          price: 1.5,
          amount: 720,
          batchNo: 'B260601',
          expDate: '2028-06-01',
        },
        {
          name: '生理盐水注射液',
          spec: '250ml',
          unit: '瓶',
          quantity: 340,
          price: 5,
          amount: 1700,
          batchNo: 'B260602',
          expDate: '2028-06-02',
        },
        {
          name: '葡萄糖注射液 5%',
          spec: '500ml',
          unit: '瓶',
          quantity: 300,
          price: 6,
          amount: 1800,
          batchNo: 'B260603',
          expDate: '2028-06-03',
        },
        {
          name: '医用脱脂纱布块',
          spec: '10cm*10cm 8层',
          unit: '包',
          quantity: 1710,
          price: 3.5,
          amount: 5985,
          batchNo: 'B260501',
          expDate: '2028-05-01',
        },
        {
          name: '一次性医用橡胶检查手套',
          spec: 'M号',
          unit: '盒',
          quantity: 1020,
          price: 25,
          amount: 25500,
          batchNo: 'B260502',
          expDate: '2028-05-02',
        },
        {
          name: '一次性使用真空采血管',
          spec: '5ml 促凝管',
          unit: '支',
          quantity: 3230,
          price: 0.8,
          amount: 2584,
          batchNo: 'B260503',
          expDate: '2028-05-03',
        },
        {
          name: '医用外科口罩',
          spec: '非无菌型',
          unit: '只',
          quantity: 10240,
          price: 0.4,
          amount: 4096,
          batchNo: 'B260504',
          expDate: '2028-05-04',
        },
      ],
    },
    fallbackBands: [
      {
        id: 'header',
        name: '页头',
        type: 'header',
        top: 0,
        bottom: 125,
        actualBottom: 125,
        visible: true,
        objects: [
          {
            id: 'h_title',
            type: 'calculated',
            formula: 'CONCAT({supplier}," 物资发货随货同行单")',
            x: 5,
            y: 15,
            width: 710,
            height: 36,
            text: '[计算]',
            color: '#000',
            background: 'transparent',
            formatType: 'number',
            decimalPlaces: 0,
            fieldName: '',
            textAlign: 'center',
            textVerticalAlign: 'middle',
            border: {
              width: 0,
              style: 'none',
              color: 'transparent',
            },
            padding: {
              top: 2,
              right: 2,
              bottom: 2,
              left: 2,
            },
            fontSize: 22,
            fontWeight: 'bold',
          },
          {
            id: 'h_line_title1',
            type: 'line',
            x: 359.5,
            y: 52,
            width: 715,
            height: 1,
            x1: 2,
            y1: 57,
            x2: 717,
            y2: 57,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
          {
            id: 'h_line_title2',
            type: 'line',
            x: 359.5,
            y: 55,
            width: 715,
            height: 1,
            x1: 2,
            y1: 60,
            x2: 717,
            y2: 60,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
          {
            id: 'h_lbl_id',
            type: 'text',
            text: '发货单号:',
            x: 4,
            y: 68,
            width: 75,
            height: 22,
            fontSize: 12,
            fontWeight: 'normal',
            color: '#333',
            background: 'transparent',
            textAlign: 'left',
            textVerticalAlign: 'middle',
            fieldName: '',
            border: {
              color: 'transparent',
            },
            padding: {
              top: 2,
              right: 2,
              bottom: 2,
              left: 2,
            },
          },
          {
            id: 'h_val_id',
            type: 'field',
            fieldName: 'id',
            x: 80,
            y: 68,
            width: 150,
            height: 22,
            fontSize: 12,
            color: '#333',
            background: 'transparent',
            textAlign: 'left',
            textVerticalAlign: 'middle',
            text: '',
            border: {
              width: 0,
              style: 'none',
              color: 'transparent',
            },
            padding: {
              top: 2,
              right: 2,
              bottom: 2,
              left: 2,
            },
          },
          {
            id: 'h_page',
            type: 'page_number',
            x: 300,
            y: 68,
            width: 120,
            height: 22,
            text: '第1页/共1页',
            fontSize: 12,
            color: '#666',
            textAlign: 'center',
            textVerticalAlign: 'middle',
            fieldName: '',
          },
          {
            id: 'h_lbl_time',
            type: 'text',
            text: '打印时间:',
            x: 500,
            y: 68,
            width: 70,
            height: 22,
            fontSize: 12,
            fontWeight: 'normal',
            color: '#333',
            background: 'transparent',
            textAlign: 'right',
            textVerticalAlign: 'middle',
            fieldName: '',
            border: {
              color: 'transparent',
            },
            padding: {
              top: 2,
              right: 6,
              bottom: 2,
              left: 2,
            },
          },
          {
            id: 'h_val_time',
            type: 'current_date',
            text: 'yyyy-MM-dd HH:mm:ss',
            x: 572,
            y: 68,
            width: 145,
            height: 22,
            fontSize: 12,
            color: '#333',
            textAlign: 'left',
            textVerticalAlign: 'middle',
            fieldName: '',
            background: 'transparent',
            border: {
              color: 'transparent',
            },
          },
          {
            id: 'h_line_top',
            type: 'line',
            x: 359.5,
            y: 90,
            width: 715,
            height: 1,
            x1: 2,
            y1: 95,
            x2: 717,
            y2: 95,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
          {
            id: 'h_line_bot',
            type: 'line',
            x: 359.5,
            y: 118,
            width: 715,
            height: 1,
            x1: 2,
            y1: 123,
            x2: 717,
            y2: 123,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
          {
            id: 'vl_h_left',
            type: 'line',
            x: 52,
            y: 90,
            width: 1,
            height: 28,
            x1: 2,
            y1: 95,
            x2: 2,
            y2: 123,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
          {
            id: 'vl_h_right',
            type: 'line',
            x: 767,
            y: 90,
            width: 1,
            height: 28,
            x1: 717,
            y1: 95,
            x2: 717,
            y2: 123,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
          {
            id: 'th_0',
            type: 'text',
            text: '序号',
            x: 2,
            y: 101,
            width: 38,
            height: 20,
            fontSize: 12,
            fontWeight: 'bold',
            color: '#333',
            background: 'transparent',
            textAlign: 'center',
            textVerticalAlign: 'middle',
            fieldName: '',
            border: {
              color: 'transparent',
            },
            padding: {
              top: 2,
              right: 2,
              bottom: 2,
              left: 2,
            },
          },
          {
            id: 'th_1',
            type: 'text',
            text: '产品名称',
            x: 40,
            y: 101,
            width: 100,
            height: 20,
            fontSize: 12,
            fontWeight: 'bold',
            color: '#333',
            background: 'transparent',
            textAlign: 'left',
            textVerticalAlign: 'middle',
            fieldName: '',
            border: {
              color: 'transparent',
            },
            padding: {
              top: 2,
              right: 2,
              bottom: 2,
              left: 2,
            },
          },
          {
            id: 'vl_h_1',
            type: 'line',
            x: 88,
            y: 90,
            width: 1,
            height: 28,
            x1: 38,
            y1: 95,
            x2: 38,
            y2: 123,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
          {
            id: 'th_2',
            type: 'text',
            text: '规格型号',
            x: 140,
            y: 101,
            width: 85,
            height: 20,
            fontSize: 12,
            fontWeight: 'bold',
            color: '#333',
            background: 'transparent',
            textAlign: 'center',
            textVerticalAlign: 'middle',
            fieldName: '',
            border: {
              color: 'transparent',
            },
            padding: {
              top: 2,
              right: 2,
              bottom: 2,
              left: 2,
            },
          },
          {
            id: 'vl_h_2',
            type: 'line',
            x: 188,
            y: 90,
            width: 1,
            height: 28,
            x1: 138,
            y1: 95,
            x2: 138,
            y2: 123,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
          {
            id: 'th_3',
            type: 'text',
            text: '批号',
            x: 225,
            y: 101,
            width: 75,
            height: 20,
            fontSize: 12,
            fontWeight: 'bold',
            color: '#333',
            background: 'transparent',
            textAlign: 'center',
            textVerticalAlign: 'middle',
            fieldName: '',
            border: {
              color: 'transparent',
            },
            padding: {
              top: 2,
              right: 2,
              bottom: 2,
              left: 2,
            },
          },
          {
            id: 'vl_h_3',
            type: 'line',
            x: 273,
            y: 90,
            width: 1,
            height: 28,
            x1: 223,
            y1: 95,
            x2: 223,
            y2: 123,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
          {
            id: 'th_4',
            type: 'text',
            text: '效期',
            x: 300,
            y: 101,
            width: 90,
            height: 20,
            fontSize: 12,
            fontWeight: 'bold',
            color: '#333',
            background: 'transparent',
            textAlign: 'center',
            textVerticalAlign: 'middle',
            fieldName: '',
            border: {
              color: 'transparent',
            },
            padding: {
              top: 2,
              right: 2,
              bottom: 2,
              left: 2,
            },
          },
          {
            id: 'vl_h_4',
            type: 'line',
            x: 348,
            y: 90,
            width: 1,
            height: 28,
            x1: 298,
            y1: 95,
            x2: 298,
            y2: 123,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
          {
            id: 'th_5',
            type: 'text',
            text: '单位',
            x: 390,
            y: 101,
            width: 40,
            height: 20,
            fontSize: 12,
            fontWeight: 'bold',
            color: '#333',
            background: 'transparent',
            textAlign: 'center',
            textVerticalAlign: 'middle',
            fieldName: '',
            border: {
              color: 'transparent',
            },
            padding: {
              top: 2,
              right: 2,
              bottom: 2,
              left: 2,
            },
          },
          {
            id: 'vl_h_5',
            type: 'line',
            x: 438,
            y: 90,
            width: 1,
            height: 28,
            x1: 388,
            y1: 95,
            x2: 388,
            y2: 123,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
          {
            id: 'th_6',
            type: 'text',
            text: '数量',
            x: 430,
            y: 101,
            width: 60,
            height: 20,
            fontSize: 12,
            fontWeight: 'bold',
            color: '#333',
            background: 'transparent',
            textAlign: 'right',
            textVerticalAlign: 'middle',
            fieldName: '',
            border: {
              color: 'transparent',
            },
            padding: {
              top: 2,
              right: 6,
              bottom: 2,
              left: 2,
            },
          },
          {
            id: 'vl_h_6',
            type: 'line',
            x: 478,
            y: 90,
            width: 1,
            height: 28,
            x1: 428,
            y1: 95,
            x2: 428,
            y2: 123,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
          {
            id: 'th_7',
            type: 'text',
            text: '单价',
            x: 490,
            y: 101,
            width: 65,
            height: 20,
            fontSize: 12,
            fontWeight: 'bold',
            color: '#333',
            background: 'transparent',
            textAlign: 'right',
            textVerticalAlign: 'middle',
            fieldName: '',
            border: {
              color: 'transparent',
            },
            padding: {
              top: 2,
              right: 6,
              bottom: 2,
              left: 2,
            },
          },
          {
            id: 'vl_h_7',
            type: 'line',
            x: 538,
            y: 90,
            width: 1,
            height: 28,
            x1: 488,
            y1: 95,
            x2: 488,
            y2: 123,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
          {
            id: 'th_8',
            type: 'text',
            text: '金额',
            x: 555,
            y: 101,
            width: 162,
            height: 20,
            fontSize: 12,
            fontWeight: 'bold',
            color: '#333',
            background: 'transparent',
            textAlign: 'right',
            textVerticalAlign: 'middle',
            fieldName: '',
            border: {
              color: 'transparent',
            },
            padding: {
              top: 2,
              right: 6,
              bottom: 2,
              left: 2,
            },
          },
          {
            id: 'vl_h_8',
            type: 'line',
            x: 603,
            y: 90,
            width: 1,
            height: 28,
            x1: 553,
            y1: 95,
            x2: 553,
            y2: 123,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
        ],
      },
      {
        id: 'detail',
        name: '明细',
        type: 'detail',
        top: 125,
        bottom: 170,
        actualBottom: 170,
        visible: true,
        objects: [
          {
            id: 'd_line_bot',
            type: 'line',
            x: 359.5,
            y: 164,
            width: 715,
            height: 1,
            x1: 2,
            y1: 169,
            x2: 717,
            y2: 169,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
          {
            id: 'vl_d_left',
            type: 'line',
            x: 52,
            y: 120,
            width: 1,
            height: 45,
            x1: 2,
            y1: 125,
            x2: 2,
            y2: 170,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
          {
            id: 'vl_d_right',
            type: 'line',
            x: 767,
            y: 120,
            width: 1,
            height: 45,
            x1: 717,
            y1: 125,
            x2: 717,
            y2: 170,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
          {
            id: 'td_0',
            type: 'calculated',
            formula: 'CONCAT({rowIndex})',
            x: 2,
            y: 126,
            width: 38,
            height: 43,
            text: '[序号]',
            color: '#333',
            background: 'transparent',
            formatType: 'number',
            decimalPlaces: 0,
            fieldName: '',
            textAlign: 'center',
            textVerticalAlign: 'middle',
            border: {
              width: 0,
              style: 'none',
              color: 'transparent',
            },
            padding: {
              top: 2,
              right: 2,
              bottom: 2,
              left: 2,
            },
          },
          {
            id: 'td_1',
            type: 'field',
            fieldName: 'products.name',
            x: 40,
            y: 126,
            width: 100,
            height: 43,
            fontSize: 12,
            color: '#333',
            background: 'transparent',
            textAlign: 'left',
            textVerticalAlign: 'middle',
            text: '',
            border: {
              width: 0,
              style: 'none',
              color: 'transparent',
            },
            padding: {
              top: 2,
              right: 2,
              bottom: 2,
              left: 2,
            },
          },
          {
            id: 'vl_d_1',
            type: 'line',
            x: 88,
            y: 120,
            width: 1,
            height: 45,
            x1: 38,
            y1: 125,
            x2: 38,
            y2: 170,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
          {
            id: 'td_2',
            type: 'field',
            fieldName: 'products.spec',
            x: 140,
            y: 126,
            width: 85,
            height: 43,
            fontSize: 12,
            color: '#333',
            background: 'transparent',
            textAlign: 'center',
            textVerticalAlign: 'middle',
            text: '',
            border: {
              width: 0,
              style: 'none',
              color: 'transparent',
            },
            padding: {
              top: 2,
              right: 2,
              bottom: 2,
              left: 2,
            },
          },
          {
            id: 'vl_d_2',
            type: 'line',
            x: 188,
            y: 120,
            width: 1,
            height: 45,
            x1: 138,
            y1: 125,
            x2: 138,
            y2: 170,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
          {
            id: 'td_3',
            type: 'field',
            fieldName: 'products.batchNo',
            x: 225,
            y: 126,
            width: 75,
            height: 43,
            fontSize: 12,
            color: '#333',
            background: 'transparent',
            textAlign: 'center',
            textVerticalAlign: 'middle',
            text: '',
            border: {
              width: 0,
              style: 'none',
              color: 'transparent',
            },
            padding: {
              top: 2,
              right: 2,
              bottom: 2,
              left: 2,
            },
          },
          {
            id: 'vl_d_3',
            type: 'line',
            x: 273,
            y: 120,
            width: 1,
            height: 45,
            x1: 223,
            y1: 125,
            x2: 223,
            y2: 170,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
          {
            id: 'td_4',
            type: 'field',
            fieldName: 'products.expDate',
            x: 300,
            y: 126,
            width: 90,
            height: 43,
            fontSize: 12,
            color: '#333',
            background: 'transparent',
            textAlign: 'center',
            textVerticalAlign: 'middle',
            text: '',
            border: {
              width: 0,
              style: 'none',
              color: 'transparent',
            },
            padding: {
              top: 2,
              right: 2,
              bottom: 2,
              left: 2,
            },
          },
          {
            id: 'vl_d_4',
            type: 'line',
            x: 348,
            y: 120,
            width: 1,
            height: 45,
            x1: 298,
            y1: 125,
            x2: 298,
            y2: 170,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
          {
            id: 'td_5',
            type: 'field',
            fieldName: 'products.unit',
            x: 390,
            y: 126,
            width: 40,
            height: 43,
            fontSize: 12,
            color: '#333',
            background: 'transparent',
            textAlign: 'center',
            textVerticalAlign: 'middle',
            text: '',
            border: {
              width: 0,
              style: 'none',
              color: 'transparent',
            },
            padding: {
              top: 2,
              right: 2,
              bottom: 2,
              left: 2,
            },
          },
          {
            id: 'vl_d_5',
            type: 'line',
            x: 438,
            y: 120,
            width: 1,
            height: 45,
            x1: 388,
            y1: 125,
            x2: 388,
            y2: 170,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
          {
            id: 'td_6',
            type: 'field',
            fieldName: 'products.quantity',
            x: 430,
            y: 126,
            width: 60,
            height: 43,
            fontSize: 12,
            color: '#333',
            background: 'transparent',
            textAlign: 'right',
            textVerticalAlign: 'middle',
            text: '',
            border: {
              width: 0,
              style: 'none',
              color: 'transparent',
            },
            padding: {
              top: 2,
              right: 6,
              bottom: 2,
              left: 2,
            },
          },
          {
            id: 'vl_d_6',
            type: 'line',
            x: 478,
            y: 120,
            width: 1,
            height: 45,
            x1: 428,
            y1: 125,
            x2: 428,
            y2: 170,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
          {
            id: 'td_7',
            type: 'field',
            fieldName: 'products.price',
            x: 490,
            y: 126,
            width: 65,
            height: 43,
            fontSize: 12,
            color: '#333',
            background: 'transparent',
            textAlign: 'right',
            textVerticalAlign: 'middle',
            text: '',
            border: {
              width: 0,
              style: 'none',
              color: 'transparent',
            },
            padding: {
              top: 2,
              right: 6,
              bottom: 2,
              left: 2,
            },
          },
          {
            id: 'vl_d_7',
            type: 'line',
            x: 538,
            y: 120,
            width: 1,
            height: 45,
            x1: 488,
            y1: 125,
            x2: 488,
            y2: 170,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
          {
            id: 'td_8',
            type: 'field',
            fieldName: 'products.amount',
            x: 555,
            y: 126,
            width: 162,
            height: 43,
            fontSize: 12,
            color: '#333',
            background: 'transparent',
            textAlign: 'right',
            textVerticalAlign: 'middle',
            text: '',
            border: {
              width: 0,
              style: 'none',
              color: 'transparent',
            },
            padding: {
              top: 2,
              right: 6,
              bottom: 2,
              left: 2,
            },
          },
          {
            id: 'vl_d_8',
            type: 'line',
            x: 603,
            y: 120,
            width: 1,
            height: 45,
            x1: 553,
            y1: 125,
            x2: 553,
            y2: 170,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
        ],
        backgroundColorFormula:
          "IIF(MOD({rowIndex}, 2) == 0,'rgb(255,255,255)', 'rgb(245,245,245)')",
      },
      {
        id: 'summary',
        name: '汇总',
        type: 'summary',
        top: 190,
        bottom: 220,
        actualBottom: 220,
        visible: true,
        objects: [
          {
            id: 's_line_top',
            type: 'line',
            x: 359.5,
            y: 185,
            width: 715,
            height: 1,
            x1: 2,
            y1: 190,
            x2: 717,
            y2: 190,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
          {
            id: 's_line_bot',
            type: 'line',
            x: 359.5,
            y: 215,
            width: 715,
            height: 1,
            x1: 2,
            y1: 220,
            x2: 717,
            y2: 220,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
          {
            id: 'vl_s_left',
            type: 'line',
            x: 52,
            y: 185,
            width: 1,
            height: 30,
            x1: 2,
            y1: 190,
            x2: 2,
            y2: 220,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
          {
            id: 'vl_s_right',
            type: 'line',
            x: 767,
            y: 185,
            width: 1,
            height: 30,
            x1: 717,
            y1: 190,
            x2: 717,
            y2: 220,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
          {
            id: 's_label',
            type: 'text',
            text: '本页合计：',
            x: 2,
            y: 191,
            width: 426,
            height: 28,
            fontSize: 12,
            fontWeight: 'bold',
            color: '#333',
            background: 'transparent',
            textAlign: 'left',
            textVerticalAlign: 'middle',
            fieldName: '',
            border: {
              color: 'transparent',
            },
            padding: {
              top: 2,
              right: 2,
              bottom: 2,
              left: 2,
            },
          },
          {
            id: 's_qty',
            type: 'calculated',
            formula: 'SUM({products.quantity})',
            x: 430,
            y: 191,
            width: 60,
            height: 28,
            text: '[合计数量]',
            color: '#333',
            background: 'transparent',
            formatType: 'number',
            decimalPlaces: 0,
            fieldName: '',
            textAlign: 'right',
            textVerticalAlign: 'middle',
            border: {
              width: 0,
              style: 'none',
              color: 'transparent',
            },
            padding: {
              top: 2,
              right: 6,
              bottom: 2,
              left: 2,
            },
          },
          {
            id: 's_amt',
            type: 'calculated',
            formula: 'SUM({products.amount})',
            x: 555,
            y: 191,
            width: 162,
            height: 28,
            text: '[合计金额]',
            color: '#333',
            background: 'transparent',
            formatType: 'currency',
            decimalPlaces: 2,
            fieldName: '',
            textAlign: 'right',
            textVerticalAlign: 'middle',
            border: {
              width: 0,
              style: 'none',
              color: 'transparent',
            },
            padding: {
              top: 2,
              right: 6,
              bottom: 2,
              left: 2,
            },
          },
          {
            id: 'vl_s_6',
            type: 'line',
            x: 478,
            y: 185,
            width: 1,
            height: 30,
            x1: 428,
            y1: 190,
            x2: 428,
            y2: 220,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
          {
            id: 'vl_s_7',
            type: 'line',
            x: 538,
            y: 185,
            width: 1,
            height: 30,
            x1: 488,
            y1: 190,
            x2: 488,
            y2: 220,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
          {
            id: 'vl_s_8',
            type: 'line',
            x: 603,
            y: 185,
            width: 1,
            height: 30,
            x1: 553,
            y1: 190,
            x2: 553,
            y2: 220,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
        ],
        summaryDisplayMode: 'perPage',
        backgroundColor: '#eee',
      },
      {
        id: 'footer',
        name: '页脚',
        type: 'footer',
        top: 245,
        bottom: 415,
        actualBottom: 415,
        visible: true,
        objects: [
          {
            id: 'f_total_lbl',
            type: 'text',
            text: '总计：',
            x: 2,
            y: 247,
            width: 426,
            height: 22,
            fontSize: 13,
            fontWeight: 'bold',
            color: '#333',
            background: 'transparent',
            textAlign: 'left',
            textVerticalAlign: 'middle',
            fieldName: '',
            border: {
              color: 'transparent',
            },
            padding: {
              top: 2,
              right: 2,
              bottom: 2,
              left: 2,
            },
          },
          {
            id: 'f_total_qty',
            type: 'field',
            fieldName: 'sendQty',
            x: 430,
            y: 247,
            width: 60,
            height: 22,
            fontSize: 13,
            color: '#333',
            background: 'transparent',
            textAlign: 'right',
            textVerticalAlign: 'middle',
            text: '',
            border: {
              width: 0,
              style: 'none',
              color: 'transparent',
            },
            padding: {
              top: 2,
              right: 6,
              bottom: 2,
              left: 2,
            },
          },
          {
            id: 'f_total_amt',
            type: 'field',
            fieldName: 'totalAmount',
            x: 555,
            y: 247,
            width: 162,
            height: 22,
            fontSize: 13,
            color: '#333',
            background: 'transparent',
            textAlign: 'right',
            textVerticalAlign: 'middle',
            text: '',
            border: {
              width: 0,
              style: 'none',
              color: 'transparent',
            },
            padding: {
              top: 2,
              right: 6,
              bottom: 2,
              left: 2,
            },
          },
          {
            id: 'f_line_total_top',
            type: 'line',
            x: 359.5,
            y: 240,
            width: 715,
            height: 1,
            x1: 2,
            y1: 245,
            x2: 717,
            y2: 245,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
          {
            id: 'f_line_total_bot',
            type: 'line',
            x: 359.5,
            y: 266,
            width: 715,
            height: 1,
            x1: 2,
            y1: 271,
            x2: 717,
            y2: 271,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
          {
            id: 'vl_f_left',
            type: 'line',
            x: 52,
            y: 240,
            width: 1,
            height: 26,
            x1: 2,
            y1: 245,
            x2: 2,
            y2: 271,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
          {
            id: 'vl_f_right',
            type: 'line',
            x: 767,
            y: 240,
            width: 1,
            height: 26,
            x1: 717,
            y1: 245,
            x2: 717,
            y2: 271,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
          {
            id: 'vl_f_qty',
            type: 'line',
            x: 478,
            y: 240,
            width: 1,
            height: 26,
            x1: 428,
            y1: 245,
            x2: 428,
            y2: 271,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
          {
            id: 'vl_f_price',
            type: 'line',
            x: 538,
            y: 240,
            width: 1,
            height: 26,
            x1: 488,
            y1: 245,
            x2: 488,
            y2: 271,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
          {
            id: 'vl_f_amt',
            type: 'line',
            x: 603,
            y: 240,
            width: 1,
            height: 26,
            x1: 553,
            y1: 245,
            x2: 553,
            y2: 271,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
          {
            id: 'f_lbl_reviewer',
            type: 'text',
            text: '审核人:',
            x: 10,
            y: 280,
            width: 65,
            height: 20,
            fontSize: 12,
            fontWeight: 'normal',
            color: '#666',
            background: 'transparent',
            textAlign: 'left',
            textVerticalAlign: 'middle',
            fieldName: '',
            border: {
              color: 'transparent',
            },
            padding: {
              top: 2,
              right: 2,
              bottom: 2,
              left: 2,
            },
          },
          {
            id: 'f_val_reviewer',
            type: 'field',
            fieldName: 'reviewer',
            x: 75,
            y: 280,
            width: 130,
            height: 20,
            fontSize: 12,
            color: '#333',
            background: 'transparent',
            textAlign: 'left',
            textVerticalAlign: 'middle',
            text: '',
            border: {
              width: 0,
              style: 'none',
              color: 'transparent',
            },
            padding: {
              top: 2,
              right: 2,
              bottom: 2,
              left: 2,
            },
          },
          {
            id: 'f_sign_line1',
            type: 'line',
            x: 140,
            y: 297,
            width: 130,
            height: 1,
            x1: 75,
            y1: 302,
            x2: 205,
            y2: 302,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
          {
            id: 'f_lbl_creator',
            type: 'text',
            text: '制单人:',
            x: 250,
            y: 280,
            width: 65,
            height: 20,
            fontSize: 12,
            fontWeight: 'normal',
            color: '#666',
            background: 'transparent',
            textAlign: 'left',
            textVerticalAlign: 'middle',
            fieldName: '',
            border: {
              color: 'transparent',
            },
            padding: {
              top: 2,
              right: 2,
              bottom: 2,
              left: 2,
            },
          },
          {
            id: 'f_val_creator',
            type: 'field',
            fieldName: 'creator',
            x: 315,
            y: 280,
            width: 130,
            height: 20,
            fontSize: 12,
            color: '#333',
            background: 'transparent',
            textAlign: 'left',
            textVerticalAlign: 'middle',
            text: '',
            border: {
              width: 0,
              style: 'none',
              color: 'transparent',
            },
            padding: {
              top: 2,
              right: 2,
              bottom: 2,
              left: 2,
            },
          },
          {
            id: 'f_sign_line2',
            type: 'line',
            x: 380,
            y: 297,
            width: 130,
            height: 1,
            x1: 315,
            y1: 302,
            x2: 445,
            y2: 302,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
          {
            id: 'f_lbl_receiver',
            type: 'text',
            text: '收货人:',
            x: 490,
            y: 280,
            width: 65,
            height: 20,
            fontSize: 12,
            fontWeight: 'normal',
            color: '#666',
            background: 'transparent',
            textAlign: 'left',
            textVerticalAlign: 'middle',
            fieldName: '',
            border: {
              color: 'transparent',
            },
            padding: {
              top: 2,
              right: 2,
              bottom: 2,
              left: 2,
            },
          },
          {
            id: 'f_val_receiver',
            type: 'field',
            fieldName: 'receiver',
            x: 555,
            y: 280,
            width: 130,
            height: 20,
            fontSize: 12,
            color: '#333',
            background: 'transparent',
            textAlign: 'left',
            textVerticalAlign: 'middle',
            text: '',
            border: {
              width: 0,
              style: 'none',
              color: 'transparent',
            },
            padding: {
              top: 2,
              right: 2,
              bottom: 2,
              left: 2,
            },
          },
          {
            id: 'f_sign_line3',
            type: 'line',
            x: 620,
            y: 297,
            width: 130,
            height: 1,
            x1: 555,
            y1: 302,
            x2: 685,
            y2: 302,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
          {
            id: 'f_lbl_remark',
            type: 'text',
            text: '备注:',
            x: 10,
            y: 315,
            width: 50,
            height: 20,
            fontSize: 12,
            fontWeight: 'normal',
            color: '#333',
            background: 'transparent',
            textAlign: 'left',
            textVerticalAlign: 'middle',
            fieldName: '',
            border: {
              color: 'transparent',
            },
            padding: {
              top: 2,
              right: 2,
              bottom: 2,
              left: 2,
            },
          },
          {
            id: 'f_val_remark',
            type: 'field',
            fieldName: 'remark',
            x: 60,
            y: 315,
            width: 640,
            height: 20,
            fontSize: 12,
            color: '#333',
            background: 'transparent',
            textAlign: 'left',
            textVerticalAlign: 'middle',
            text: '',
            border: {
              width: 0,
              style: 'none',
              color: 'transparent',
            },
            padding: {
              top: 2,
              right: 2,
              bottom: 2,
              left: 2,
            },
          },
          {
            id: 'f_remark_line',
            type: 'line',
            x: 380,
            y: 332,
            width: 640,
            height: 1,
            x1: 60,
            y1: 337,
            x2: 700,
            y2: 337,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
        ],
      },
    ],
    fallbackPageSettings: {
      paperSize: 'A4',
      width: 210,
      height: 297,
      unit: 'mm',
      margins: {
        top: 10,
        bottom: 10,
        left: 10,
        right: 10,
      },
      orientation: 'portrait',
    },
  },
  {
    key: 'c_finance_statement',
    name: '财务结算对账单模板',
    code: 'c_finance_statement',
    description: '用于医院与供应商之间的财务结算与对账。',
    dataFields: [
      {
        name: 'statementNo',
        label: '对账单号',
        type: 'string',
      },
      {
        name: 'hospital',
        label: '结算医院',
        type: 'string',
      },
      {
        name: 'supplier',
        label: '供应商',
        type: 'string',
      },
      {
        name: 'period',
        label: '结算期间',
        type: 'string',
      },
      {
        name: 'totalQuantity',
        label: '结算总数量',
        type: 'number',
      },
      {
        name: 'totalAmount',
        label: '总金额',
        type: 'currency',
      },
      {
        name: 'totalChinese',
        label: '大写金额',
        type: 'string',
      },
      {
        name: 'creator',
        label: '制单人',
        type: 'string',
      },
      {
        name: 'reviewer',
        label: '审核人',
        type: 'string',
      },
      {
        name: 'receiver',
        label: '接收人',
        type: 'string',
      },
      {
        name: 'remark',
        label: '备注',
        type: 'string',
      },
      {
        name: 'sendTime',
        label: '制单时间',
        type: 'string',
      },
      {
        name: 'products',
        label: '对账明细',
        type: 'array',
        children: [
          {
            name: 'name',
            label: '物资名称',
            type: 'string',
          },
          {
            name: 'spec',
            label: '规格型号',
            type: 'string',
          },
          {
            name: 'unit',
            label: '单位',
            type: 'string',
          },
          {
            name: 'quantity',
            label: '结算数量',
            type: 'number',
          },
          {
            name: 'price',
            label: '单价',
            type: 'currency',
          },
          {
            name: 'amount',
            label: '结算金额',
            type: 'currency',
          },
        ],
      },
    ],
    mockData: {
      statementNo: 'ST-20260630001',
      hospital: '上海市第一人民医院',
      supplier: '国药控股股份有限公司',
      period: '2026-06-01 至 2026-06-30',
      totalQuantity: 74000,
      totalAmount: 204878,
      totalChinese: '伍万陆仟伍佰圆整',
      creator: '张美玲',
      reviewer: '郑建平',
      receiver: '陈伟国',
      remark: '按月度结算协议，账期30天，请尽快安排付款。',
      sendTime: '2026-06-30 16:30:00',
      products: [
        {
          name: '一次性精密输液器',
          spec: '带针 0.5',
          unit: '支',
          quantity: 2000,
          price: 5.5,
          amount: 11000,
        },
        {
          name: '医用无菌敷贴',
          spec: '10cm * 10cm',
          unit: '片',
          quantity: 5010,
          price: 1.2,
          amount: 6012,
        },
        {
          name: '医用脱脂纱布块',
          spec: '10cm*10cm 8层',
          unit: '包',
          quantity: 1520,
          price: 3.5,
          amount: 5320,
        },
        {
          name: '一次性医用橡胶检查手套',
          spec: 'M号',
          unit: '盒',
          quantity: 830,
          price: 25,
          amount: 20750,
        },
        {
          name: '一次性使用真空采血管',
          spec: '5ml 促凝管',
          unit: '支',
          quantity: 3040,
          price: 0.8,
          amount: 2432,
        },
        {
          name: '医用外科口罩',
          spec: '非无菌型',
          unit: '只',
          quantity: 10050,
          price: 0.4,
          amount: 4020,
        },
        {
          name: '一次性使用无菌导尿管',
          spec: '16Fr 双腔',
          unit: '根',
          quantity: 560,
          price: 8.5,
          amount: 4760,
        },
        {
          name: '免洗手消毒凝胶',
          spec: '500ml/瓶',
          unit: '瓶',
          quantity: 270,
          price: 18,
          amount: 4860,
        },
        {
          name: '一次性精密输液器',
          spec: '带针 0.5',
          unit: '支',
          quantity: 2080,
          price: 5.5,
          amount: 11440,
        },
        {
          name: '医用无菌敷贴',
          spec: '10cm * 10cm',
          unit: '片',
          quantity: 5090,
          price: 1.2,
          amount: 6108,
        },
        {
          name: '医用脱脂纱布块',
          spec: '10cm*10cm 8层',
          unit: '包',
          quantity: 1600,
          price: 3.5,
          amount: 5600,
        },
        {
          name: '一次性医用橡胶检查手套',
          spec: 'M号',
          unit: '盒',
          quantity: 910,
          price: 25,
          amount: 22750,
        },
        {
          name: '一次性使用真空采血管',
          spec: '5ml 促凝管',
          unit: '支',
          quantity: 3120,
          price: 0.8,
          amount: 2496,
        },
        {
          name: '医用外科口罩',
          spec: '非无菌型',
          unit: '只',
          quantity: 10130,
          price: 0.4,
          amount: 4052,
        },
        {
          name: '一次性使用无菌导尿管',
          spec: '16Fr 双腔',
          unit: '根',
          quantity: 640,
          price: 8.5,
          amount: 5440,
        },
        {
          name: '免洗手消毒凝胶',
          spec: '500ml/瓶',
          unit: '瓶',
          quantity: 350,
          price: 18,
          amount: 6300,
        },
        {
          name: '一次性精密输液器',
          spec: '带针 0.5',
          unit: '支',
          quantity: 2160,
          price: 5.5,
          amount: 11880,
        },
        {
          name: '医用无菌敷贴',
          spec: '10cm * 10cm',
          unit: '片',
          quantity: 5170,
          price: 1.2,
          amount: 6204,
        },
        {
          name: '医用脱脂纱布块',
          spec: '10cm*10cm 8层',
          unit: '包',
          quantity: 1680,
          price: 3.5,
          amount: 5880,
        },
        {
          name: '一次性医用橡胶检查手套',
          spec: 'M号',
          unit: '盒',
          quantity: 990,
          price: 25,
          amount: 24750,
        },
        {
          name: '一次性使用真空采血管',
          spec: '5ml 促凝管',
          unit: '支',
          quantity: 3200,
          price: 0.8,
          amount: 2560,
        },
        {
          name: '医用外科口罩',
          spec: '非无菌型',
          unit: '只',
          quantity: 10210,
          price: 0.4,
          amount: 4084,
        },
        {
          name: '一次性使用无菌导尿管',
          spec: '16Fr 双腔',
          unit: '根',
          quantity: 720,
          price: 8.5,
          amount: 6120,
        },
        {
          name: '免洗手消毒凝胶',
          spec: '500ml/瓶',
          unit: '瓶',
          quantity: 430,
          price: 18,
          amount: 7740,
        },
        {
          name: '一次性精密输液器',
          spec: '带针 0.5',
          unit: '支',
          quantity: 2240,
          price: 5.5,
          amount: 12320,
        },
      ],
    },
    fallbackBands: [
      {
        id: 'header',
        name: '页头',
        type: 'header',
        top: 0,
        bottom: 155,
        actualBottom: 155,
        visible: true,
        objects: [
          {
            id: 'h_title',
            type: 'calculated',
            formula: 'CONCAT({hospital}," 结算对账单")',
            x: 5,
            y: 15,
            width: 710,
            height: 36,
            text: '[计算]',
            color: '#000',
            background: 'transparent',
            formatType: 'number',
            decimalPlaces: 0,
            fieldName: '',
            textAlign: 'center',
            textVerticalAlign: 'middle',
            border: {
              width: 0,
              style: 'none',
              color: 'transparent',
            },
            padding: {
              top: 2,
              right: 2,
              bottom: 2,
              left: 2,
            },
            fontSize: 22,
            fontWeight: 'bold',
          },
          {
            id: 'h_line_title1',
            type: 'line',
            x: 359.5,
            y: 52,
            width: 715,
            height: 1,
            x1: 2,
            y1: 57,
            x2: 717,
            y2: 57,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
          {
            id: 'h_line_title2',
            type: 'line',
            x: 359.5,
            y: 55,
            width: 715,
            height: 1,
            x1: 2,
            y1: 60,
            x2: 717,
            y2: 60,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
          {
            id: 'h_lbl_no',
            type: 'text',
            text: '对账单号:',
            x: 4,
            y: 65,
            width: 75,
            height: 20,
            fontSize: 12,
            fontWeight: 'normal',
            color: '#333',
            background: 'transparent',
            textAlign: 'left',
            textVerticalAlign: 'middle',
            fieldName: '',
            border: {
              color: 'transparent',
            },
            padding: {
              top: 2,
              right: 2,
              bottom: 2,
              left: 2,
            },
          },
          {
            id: 'h_val_no',
            type: 'field',
            fieldName: 'statementNo',
            x: 80,
            y: 65,
            width: 160,
            height: 20,
            fontSize: 12,
            color: '#333',
            background: 'transparent',
            textAlign: 'left',
            textVerticalAlign: 'middle',
            text: '',
            border: {
              width: 0,
              style: 'none',
              color: 'transparent',
            },
            padding: {
              top: 2,
              right: 2,
              bottom: 2,
              left: 2,
            },
          },
          {
            id: 'h_page',
            type: 'page_number',
            x: 300,
            y: 65,
            width: 120,
            height: 20,
            text: '第1页/共1页',
            fontSize: 12,
            color: '#666',
            textAlign: 'center',
            textVerticalAlign: 'middle',
            fieldName: '',
          },
          {
            id: 'h_lbl_time',
            type: 'text',
            text: '打印时间:',
            x: 500,
            y: 65,
            width: 70,
            height: 20,
            fontSize: 12,
            fontWeight: 'normal',
            color: '#333',
            background: 'transparent',
            textAlign: 'right',
            textVerticalAlign: 'middle',
            fieldName: '',
            border: {
              color: 'transparent',
            },
            padding: {
              top: 2,
              right: 6,
              bottom: 2,
              left: 2,
            },
          },
          {
            id: 'h_val_time',
            type: 'current_date',
            text: 'yyyy-MM-dd HH:mm:ss',
            x: 572,
            y: 65,
            width: 145,
            height: 20,
            fontSize: 12,
            color: '#333',
            textAlign: 'left',
            textVerticalAlign: 'middle',
            fieldName: '',
            background: 'transparent',
            border: {
              color: 'transparent',
            },
          },
          {
            id: 'h_lbl_period',
            type: 'text',
            text: '结算期间:',
            x: 4,
            y: 88,
            width: 75,
            height: 20,
            fontSize: 12,
            fontWeight: 'normal',
            color: '#333',
            background: 'transparent',
            textAlign: 'left',
            textVerticalAlign: 'middle',
            fieldName: '',
            border: {
              color: 'transparent',
            },
            padding: {
              top: 2,
              right: 2,
              bottom: 2,
              left: 2,
            },
          },
          {
            id: 'h_val_period',
            type: 'field',
            fieldName: 'period',
            x: 80,
            y: 88,
            width: 230,
            height: 20,
            fontSize: 12,
            color: '#333',
            background: 'transparent',
            textAlign: 'left',
            textVerticalAlign: 'middle',
            text: '',
            border: {
              width: 0,
              style: 'none',
              color: 'transparent',
            },
            padding: {
              top: 2,
              right: 2,
              bottom: 2,
              left: 2,
            },
          },
          {
            id: 'h_lbl_supplier',
            type: 'text',
            text: '供应商:',
            x: 320,
            y: 88,
            width: 65,
            height: 20,
            fontSize: 12,
            fontWeight: 'normal',
            color: '#333',
            background: 'transparent',
            textAlign: 'left',
            textVerticalAlign: 'middle',
            fieldName: '',
            border: {
              color: 'transparent',
            },
            padding: {
              top: 2,
              right: 2,
              bottom: 2,
              left: 2,
            },
          },
          {
            id: 'h_val_supplier',
            type: 'field',
            fieldName: 'supplier',
            x: 385,
            y: 88,
            width: 330,
            height: 20,
            fontSize: 12,
            color: '#333',
            background: 'transparent',
            textAlign: 'left',
            textVerticalAlign: 'middle',
            text: '',
            border: {
              width: 0,
              style: 'none',
              color: 'transparent',
            },
            padding: {
              top: 2,
              right: 2,
              bottom: 2,
              left: 2,
            },
          },
          {
            id: 'h_line_top',
            type: 'line',
            x: 359.5,
            y: 122,
            width: 715,
            height: 1,
            x1: 2,
            y1: 127,
            x2: 717,
            y2: 127,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
          {
            id: 'h_line_bot',
            type: 'line',
            x: 359.5,
            y: 148,
            width: 715,
            height: 1,
            x1: 2,
            y1: 153,
            x2: 717,
            y2: 153,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
          {
            id: 'vl_h_left',
            type: 'line',
            x: 52,
            y: 122,
            width: 1,
            height: 26,
            x1: 2,
            y1: 127,
            x2: 2,
            y2: 153,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
          {
            id: 'vl_h_right',
            type: 'line',
            x: 767,
            y: 122,
            width: 1,
            height: 26,
            x1: 717,
            y1: 127,
            x2: 717,
            y2: 153,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
          {
            id: 'th_0',
            type: 'text',
            text: '序号',
            x: 2,
            y: 133,
            width: 42,
            height: 20,
            fontSize: 12,
            fontWeight: 'bold',
            color: '#333',
            background: 'transparent',
            textAlign: 'center',
            textVerticalAlign: 'middle',
            fieldName: '',
            border: {
              color: 'transparent',
            },
            padding: {
              top: 2,
              right: 2,
              bottom: 2,
              left: 2,
            },
          },
          {
            id: 'th_1',
            type: 'text',
            text: '物资名称',
            x: 44,
            y: 133,
            width: 196,
            height: 20,
            fontSize: 12,
            fontWeight: 'bold',
            color: '#333',
            background: 'transparent',
            textAlign: 'left',
            textVerticalAlign: 'middle',
            fieldName: '',
            border: {
              color: 'transparent',
            },
            padding: {
              top: 2,
              right: 2,
              bottom: 2,
              left: 2,
            },
          },
          {
            id: 'vl_h_1',
            type: 'line',
            x: 92,
            y: 122,
            width: 1,
            height: 26,
            x1: 42,
            y1: 127,
            x2: 42,
            y2: 153,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
          {
            id: 'th_2',
            type: 'text',
            text: '规格型号',
            x: 240,
            y: 133,
            width: 115,
            height: 20,
            fontSize: 12,
            fontWeight: 'bold',
            color: '#333',
            background: 'transparent',
            textAlign: 'center',
            textVerticalAlign: 'middle',
            fieldName: '',
            border: {
              color: 'transparent',
            },
            padding: {
              top: 2,
              right: 2,
              bottom: 2,
              left: 2,
            },
          },
          {
            id: 'vl_h_2',
            type: 'line',
            x: 288,
            y: 122,
            width: 1,
            height: 26,
            x1: 238,
            y1: 127,
            x2: 238,
            y2: 153,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
          {
            id: 'th_3',
            type: 'text',
            text: '单位',
            x: 355,
            y: 133,
            width: 50,
            height: 20,
            fontSize: 12,
            fontWeight: 'bold',
            color: '#333',
            background: 'transparent',
            textAlign: 'center',
            textVerticalAlign: 'middle',
            fieldName: '',
            border: {
              color: 'transparent',
            },
            padding: {
              top: 2,
              right: 2,
              bottom: 2,
              left: 2,
            },
          },
          {
            id: 'vl_h_3',
            type: 'line',
            x: 403,
            y: 122,
            width: 1,
            height: 26,
            x1: 353,
            y1: 127,
            x2: 353,
            y2: 153,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
          {
            id: 'th_4',
            type: 'text',
            text: '数量',
            x: 405,
            y: 133,
            width: 75,
            height: 20,
            fontSize: 12,
            fontWeight: 'bold',
            color: '#333',
            background: 'transparent',
            textAlign: 'right',
            textVerticalAlign: 'middle',
            fieldName: '',
            border: {
              color: 'transparent',
            },
            padding: {
              top: 2,
              right: 6,
              bottom: 2,
              left: 2,
            },
          },
          {
            id: 'vl_h_4',
            type: 'line',
            x: 453,
            y: 122,
            width: 1,
            height: 26,
            x1: 403,
            y1: 127,
            x2: 403,
            y2: 153,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
          {
            id: 'th_5',
            type: 'text',
            text: '单价',
            x: 480,
            y: 133,
            width: 75,
            height: 20,
            fontSize: 12,
            fontWeight: 'bold',
            color: '#333',
            background: 'transparent',
            textAlign: 'right',
            textVerticalAlign: 'middle',
            fieldName: '',
            border: {
              color: 'transparent',
            },
            padding: {
              top: 2,
              right: 6,
              bottom: 2,
              left: 2,
            },
          },
          {
            id: 'vl_h_5',
            type: 'line',
            x: 528,
            y: 122,
            width: 1,
            height: 26,
            x1: 478,
            y1: 127,
            x2: 478,
            y2: 153,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
          {
            id: 'th_6',
            type: 'text',
            text: '金额',
            x: 555,
            y: 133,
            width: 162,
            height: 20,
            fontSize: 12,
            fontWeight: 'bold',
            color: '#333',
            background: 'transparent',
            textAlign: 'right',
            textVerticalAlign: 'middle',
            fieldName: '',
            border: {
              color: 'transparent',
            },
            padding: {
              top: 2,
              right: 6,
              bottom: 2,
              left: 2,
            },
          },
          {
            id: 'vl_h_6',
            type: 'line',
            x: 603,
            y: 122,
            width: 1,
            height: 26,
            x1: 553,
            y1: 127,
            x2: 553,
            y2: 153,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
        ],
      },
      {
        id: 'detail',
        name: '明细',
        type: 'detail',
        top: 155,
        bottom: 200,
        actualBottom: 200,
        visible: true,
        objects: [
          {
            id: 'd_line_bot',
            type: 'line',
            x: 359.5,
            y: 194,
            width: 715,
            height: 1,
            x1: 2,
            y1: 199,
            x2: 717,
            y2: 199,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
          {
            id: 'vl_d_left',
            type: 'line',
            x: 52,
            y: 150,
            width: 1,
            height: 45,
            x1: 2,
            y1: 155,
            x2: 2,
            y2: 200,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
          {
            id: 'vl_d_right',
            type: 'line',
            x: 767,
            y: 150,
            width: 1,
            height: 45,
            x1: 717,
            y1: 155,
            x2: 717,
            y2: 200,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
          {
            id: 'td_0',
            type: 'calculated',
            formula: 'CONCAT({rowIndex})',
            x: 2,
            y: 156,
            width: 42,
            height: 43,
            text: '[序号]',
            color: '#333',
            background: 'transparent',
            formatType: 'number',
            decimalPlaces: 0,
            fieldName: '',
            textAlign: 'center',
            textVerticalAlign: 'middle',
            border: {
              width: 0,
              style: 'none',
              color: 'transparent',
            },
            padding: {
              top: 2,
              right: 2,
              bottom: 2,
              left: 2,
            },
          },
          {
            id: 'td_1',
            type: 'field',
            fieldName: 'products.name',
            x: 44,
            y: 156,
            width: 196,
            height: 43,
            fontSize: 12,
            color: '#333',
            background: 'transparent',
            textAlign: 'left',
            textVerticalAlign: 'middle',
            text: '',
            border: {
              width: 0,
              style: 'none',
              color: 'transparent',
            },
            padding: {
              top: 2,
              right: 2,
              bottom: 2,
              left: 2,
            },
          },
          {
            id: 'vl_d_1',
            type: 'line',
            x: 92,
            y: 150,
            width: 1,
            height: 45,
            x1: 42,
            y1: 155,
            x2: 42,
            y2: 200,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
          {
            id: 'td_2',
            type: 'field',
            fieldName: 'products.spec',
            x: 240,
            y: 156,
            width: 115,
            height: 43,
            fontSize: 12,
            color: '#333',
            background: 'transparent',
            textAlign: 'center',
            textVerticalAlign: 'middle',
            text: '',
            border: {
              width: 0,
              style: 'none',
              color: 'transparent',
            },
            padding: {
              top: 2,
              right: 2,
              bottom: 2,
              left: 2,
            },
          },
          {
            id: 'vl_d_2',
            type: 'line',
            x: 288,
            y: 150,
            width: 1,
            height: 45,
            x1: 238,
            y1: 155,
            x2: 238,
            y2: 200,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
          {
            id: 'td_3',
            type: 'field',
            fieldName: 'products.unit',
            x: 355,
            y: 156,
            width: 50,
            height: 43,
            fontSize: 12,
            color: '#333',
            background: 'transparent',
            textAlign: 'center',
            textVerticalAlign: 'middle',
            text: '',
            border: {
              width: 0,
              style: 'none',
              color: 'transparent',
            },
            padding: {
              top: 2,
              right: 2,
              bottom: 2,
              left: 2,
            },
          },
          {
            id: 'vl_d_3',
            type: 'line',
            x: 403,
            y: 150,
            width: 1,
            height: 45,
            x1: 353,
            y1: 155,
            x2: 353,
            y2: 200,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
          {
            id: 'td_4',
            type: 'field',
            fieldName: 'products.quantity',
            x: 405,
            y: 156,
            width: 75,
            height: 43,
            fontSize: 12,
            color: '#333',
            background: 'transparent',
            textAlign: 'right',
            textVerticalAlign: 'middle',
            text: '',
            border: {
              width: 0,
              style: 'none',
              color: 'transparent',
            },
            padding: {
              top: 2,
              right: 6,
              bottom: 2,
              left: 2,
            },
          },
          {
            id: 'vl_d_4',
            type: 'line',
            x: 453,
            y: 150,
            width: 1,
            height: 45,
            x1: 403,
            y1: 155,
            x2: 403,
            y2: 200,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
          {
            id: 'td_5',
            type: 'field',
            fieldName: 'products.price',
            x: 480,
            y: 156,
            width: 75,
            height: 43,
            fontSize: 12,
            color: '#333',
            background: 'transparent',
            textAlign: 'right',
            textVerticalAlign: 'middle',
            text: '',
            border: {
              width: 0,
              style: 'none',
              color: 'transparent',
            },
            padding: {
              top: 2,
              right: 6,
              bottom: 2,
              left: 2,
            },
          },
          {
            id: 'vl_d_5',
            type: 'line',
            x: 528,
            y: 150,
            width: 1,
            height: 45,
            x1: 478,
            y1: 155,
            x2: 478,
            y2: 200,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
          {
            id: 'td_6',
            type: 'field',
            fieldName: 'products.amount',
            x: 555,
            y: 156,
            width: 162,
            height: 43,
            fontSize: 12,
            color: '#333',
            background: 'transparent',
            textAlign: 'right',
            textVerticalAlign: 'middle',
            text: '',
            border: {
              width: 0,
              style: 'none',
              color: 'transparent',
            },
            padding: {
              top: 2,
              right: 6,
              bottom: 2,
              left: 2,
            },
          },
          {
            id: 'vl_d_6',
            type: 'line',
            x: 603,
            y: 150,
            width: 1,
            height: 45,
            x1: 553,
            y1: 155,
            x2: 553,
            y2: 200,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
        ],
        backgroundColorFormula:
          "IIF(MOD({rowIndex}, 2) == 0,'rgb(255,255,255)', 'rgb(245,245,245)')",
      },
      {
        id: 'summary',
        name: '汇总',
        type: 'summary',
        top: 220,
        bottom: 250,
        actualBottom: 250,
        visible: true,
        objects: [
          {
            id: 's_line_top',
            type: 'line',
            x: 359.5,
            y: 215,
            width: 715,
            height: 1,
            x1: 2,
            y1: 220,
            x2: 717,
            y2: 220,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
          {
            id: 's_line_bot',
            type: 'line',
            x: 359.5,
            y: 245,
            width: 715,
            height: 1,
            x1: 2,
            y1: 250,
            x2: 717,
            y2: 250,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
          {
            id: 'vl_s_left',
            type: 'line',
            x: 52,
            y: 215,
            width: 1,
            height: 30,
            x1: 2,
            y1: 220,
            x2: 2,
            y2: 250,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
          {
            id: 'vl_s_right',
            type: 'line',
            x: 767,
            y: 215,
            width: 1,
            height: 30,
            x1: 717,
            y1: 220,
            x2: 717,
            y2: 250,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
          {
            id: 's_label',
            type: 'text',
            text: '本页合计：',
            x: 2,
            y: 221,
            width: 401,
            height: 28,
            fontSize: 12,
            fontWeight: 'bold',
            color: '#333',
            background: 'transparent',
            textAlign: 'left',
            textVerticalAlign: 'middle',
            fieldName: '',
            border: {
              color: 'transparent',
            },
            padding: {
              top: 2,
              right: 2,
              bottom: 2,
              left: 2,
            },
          },
          {
            id: 's_qty',
            type: 'calculated',
            formula: 'SUM({products.quantity})',
            x: 405,
            y: 221,
            width: 75,
            height: 28,
            text: '[合计数量]',
            color: '#333',
            background: 'transparent',
            formatType: 'number',
            decimalPlaces: 0,
            fieldName: '',
            textAlign: 'right',
            textVerticalAlign: 'middle',
            border: {
              width: 0,
              style: 'none',
              color: 'transparent',
            },
            padding: {
              top: 2,
              right: 6,
              bottom: 2,
              left: 2,
            },
          },
          {
            id: 's_amt',
            type: 'calculated',
            formula: 'SUM({products.amount})',
            x: 555,
            y: 221,
            width: 162,
            height: 28,
            text: '[合计金额]',
            color: '#333',
            background: 'transparent',
            formatType: 'currency',
            decimalPlaces: 2,
            fieldName: '',
            textAlign: 'right',
            textVerticalAlign: 'middle',
            border: {
              width: 0,
              style: 'none',
              color: 'transparent',
            },
            padding: {
              top: 2,
              right: 6,
              bottom: 2,
              left: 2,
            },
          },
          {
            id: 'vl_s_4',
            type: 'line',
            x: 453,
            y: 215,
            width: 1,
            height: 30,
            x1: 403,
            y1: 220,
            x2: 403,
            y2: 250,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
          {
            id: 'vl_s_5',
            type: 'line',
            x: 528,
            y: 215,
            width: 1,
            height: 30,
            x1: 478,
            y1: 220,
            x2: 478,
            y2: 250,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
          {
            id: 'vl_s_6',
            type: 'line',
            x: 603,
            y: 215,
            width: 1,
            height: 30,
            x1: 553,
            y1: 220,
            x2: 553,
            y2: 250,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
        ],
        summaryDisplayMode: 'perPage',
        backgroundColor: '#eee',
      },
      {
        id: 'footer',
        name: '页脚',
        type: 'footer',
        top: 275,
        bottom: 445,
        actualBottom: 445,
        visible: true,
        objects: [
          {
            id: 'f_total_lbl',
            type: 'text',
            text: '总计：',
            x: 2,
            y: 277,
            width: 401,
            height: 22,
            fontSize: 13,
            fontWeight: 'bold',
            color: '#333',
            background: 'transparent',
            textAlign: 'left',
            textVerticalAlign: 'middle',
            fieldName: '',
            border: {
              color: 'transparent',
            },
            padding: {
              top: 2,
              right: 2,
              bottom: 2,
              left: 2,
            },
          },
          {
            id: 'f_total_qty',
            type: 'field',
            fieldName: 'totalQuantity',
            x: 405,
            y: 277,
            width: 75,
            height: 22,
            fontSize: 13,
            color: '#333',
            background: 'transparent',
            textAlign: 'right',
            textVerticalAlign: 'middle',
            text: '',
            border: {
              width: 0,
              style: 'none',
              color: 'transparent',
            },
            padding: {
              top: 2,
              right: 6,
              bottom: 2,
              left: 2,
            },
          },
          {
            id: 'f_total_amt',
            type: 'field',
            fieldName: 'totalAmount',
            x: 555,
            y: 277,
            width: 162,
            height: 22,
            fontSize: 13,
            color: '#333',
            background: 'transparent',
            textAlign: 'right',
            textVerticalAlign: 'middle',
            text: '',
            border: {
              width: 0,
              style: 'none',
              color: 'transparent',
            },
            padding: {
              top: 2,
              right: 6,
              bottom: 2,
              left: 2,
            },
          },
          {
            id: 'f_line_total_top',
            type: 'line',
            x: 359.5,
            y: 270,
            width: 715,
            height: 1,
            x1: 2,
            y1: 275,
            x2: 717,
            y2: 275,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
          {
            id: 'f_line_total_bot',
            type: 'line',
            x: 359.5,
            y: 296,
            width: 715,
            height: 1,
            x1: 2,
            y1: 301,
            x2: 717,
            y2: 301,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
          {
            id: 'vl_f_left',
            type: 'line',
            x: 52,
            y: 270,
            width: 1,
            height: 26,
            x1: 2,
            y1: 275,
            x2: 2,
            y2: 301,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
          {
            id: 'vl_f_right',
            type: 'line',
            x: 767,
            y: 270,
            width: 1,
            height: 26,
            x1: 717,
            y1: 275,
            x2: 717,
            y2: 301,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
          {
            id: 'vl_f_qty',
            type: 'line',
            x: 453,
            y: 270,
            width: 1,
            height: 26,
            x1: 403,
            y1: 275,
            x2: 403,
            y2: 301,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
          {
            id: 'vl_f_price',
            type: 'line',
            x: 528,
            y: 270,
            width: 1,
            height: 26,
            x1: 478,
            y1: 275,
            x2: 478,
            y2: 301,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
          {
            id: 'vl_f_amt',
            type: 'line',
            x: 603,
            y: 270,
            width: 1,
            height: 26,
            x1: 553,
            y1: 275,
            x2: 553,
            y2: 301,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
          {
            id: 'f_lbl_reviewer',
            type: 'text',
            text: '审核人:',
            x: 10,
            y: 310,
            width: 65,
            height: 20,
            fontSize: 12,
            fontWeight: 'normal',
            color: '#666',
            background: 'transparent',
            textAlign: 'left',
            textVerticalAlign: 'middle',
            fieldName: '',
            border: {
              color: 'transparent',
            },
            padding: {
              top: 2,
              right: 2,
              bottom: 2,
              left: 2,
            },
          },
          {
            id: 'f_val_reviewer',
            type: 'field',
            fieldName: 'reviewer',
            x: 75,
            y: 310,
            width: 130,
            height: 20,
            fontSize: 12,
            color: '#333',
            background: 'transparent',
            textAlign: 'left',
            textVerticalAlign: 'middle',
            text: '',
            border: {
              width: 0,
              style: 'none',
              color: 'transparent',
            },
            padding: {
              top: 2,
              right: 2,
              bottom: 2,
              left: 2,
            },
          },
          {
            id: 'f_sign_line1',
            type: 'line',
            x: 140,
            y: 327,
            width: 130,
            height: 1,
            x1: 75,
            y1: 332,
            x2: 205,
            y2: 332,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
          {
            id: 'f_lbl_creator',
            type: 'text',
            text: '制单人:',
            x: 250,
            y: 310,
            width: 65,
            height: 20,
            fontSize: 12,
            fontWeight: 'normal',
            color: '#666',
            background: 'transparent',
            textAlign: 'left',
            textVerticalAlign: 'middle',
            fieldName: '',
            border: {
              color: 'transparent',
            },
            padding: {
              top: 2,
              right: 2,
              bottom: 2,
              left: 2,
            },
          },
          {
            id: 'f_val_creator',
            type: 'field',
            fieldName: 'creator',
            x: 315,
            y: 310,
            width: 130,
            height: 20,
            fontSize: 12,
            color: '#333',
            background: 'transparent',
            textAlign: 'left',
            textVerticalAlign: 'middle',
            text: '',
            border: {
              width: 0,
              style: 'none',
              color: 'transparent',
            },
            padding: {
              top: 2,
              right: 2,
              bottom: 2,
              left: 2,
            },
          },
          {
            id: 'f_sign_line2',
            type: 'line',
            x: 380,
            y: 327,
            width: 130,
            height: 1,
            x1: 315,
            y1: 332,
            x2: 445,
            y2: 332,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
          {
            id: 'f_lbl_receiver',
            type: 'text',
            text: '接收人:',
            x: 490,
            y: 310,
            width: 65,
            height: 20,
            fontSize: 12,
            fontWeight: 'normal',
            color: '#666',
            background: 'transparent',
            textAlign: 'left',
            textVerticalAlign: 'middle',
            fieldName: '',
            border: {
              color: 'transparent',
            },
            padding: {
              top: 2,
              right: 2,
              bottom: 2,
              left: 2,
            },
          },
          {
            id: 'f_val_receiver',
            type: 'field',
            fieldName: 'receiver',
            x: 555,
            y: 310,
            width: 130,
            height: 20,
            fontSize: 12,
            color: '#333',
            background: 'transparent',
            textAlign: 'left',
            textVerticalAlign: 'middle',
            text: '',
            border: {
              width: 0,
              style: 'none',
              color: 'transparent',
            },
            padding: {
              top: 2,
              right: 2,
              bottom: 2,
              left: 2,
            },
          },
          {
            id: 'f_sign_line3',
            type: 'line',
            x: 620,
            y: 327,
            width: 130,
            height: 1,
            x1: 555,
            y1: 332,
            x2: 685,
            y2: 332,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
          {
            id: 'f_lbl_remark',
            type: 'text',
            text: '备注:',
            x: 10,
            y: 345,
            width: 50,
            height: 20,
            fontSize: 12,
            fontWeight: 'normal',
            color: '#333',
            background: 'transparent',
            textAlign: 'left',
            textVerticalAlign: 'middle',
            fieldName: '',
            border: {
              color: 'transparent',
            },
            padding: {
              top: 2,
              right: 2,
              bottom: 2,
              left: 2,
            },
          },
          {
            id: 'f_val_remark',
            type: 'field',
            fieldName: 'remark',
            x: 60,
            y: 345,
            width: 640,
            height: 20,
            fontSize: 12,
            color: '#333',
            background: 'transparent',
            textAlign: 'left',
            textVerticalAlign: 'middle',
            text: '',
            border: {
              width: 0,
              style: 'none',
              color: 'transparent',
            },
            padding: {
              top: 2,
              right: 2,
              bottom: 2,
              left: 2,
            },
          },
          {
            id: 'f_remark_line',
            type: 'line',
            x: 380,
            y: 362,
            width: 640,
            height: 1,
            x1: 60,
            y1: 367,
            x2: 700,
            y2: 367,
            strokeWidth: 1,
            color: '#000',
            lineStyle: 'solid',
            text: '',
            fieldName: '',
          },
        ],
      },
    ],
    fallbackPageSettings: {
      paperSize: 'A4',
      width: 210,
      height: 297,
      unit: 'mm',
      margins: {
        top: 10,
        bottom: 10,
        left: 10,
        right: 10,
      },
      orientation: 'portrait',
    },
  },
];
