// 4 个单据的 Mock 数据字典、数据与默认布局配置文件

export interface PrintTemplate {
  key: string;
  name: string;
  code: string;
  description: string;
  dataFields: any[];
  mockData: any;
  fallbackBands: any[];
  fallbackPageSettings: any;
}

// 默认页面大小 A4 纵向
export const defaultPageSettings = {
  paperSize: 'A4',
  width: 210,
  height: 297,
  unit: 'mm',
  margins: { top: 10, bottom: 10, left: 10, right: 10 },
  orientation: 'portrait',
};

export const mockTemplates: PrintTemplate[] = [
  {
    key: 'c_delivery_order',
    name: '物资发货单模板',
    code: 'c_delivery_order',
    description:
      '用于供应商向医院发送物资时的随货同行单据打印（跨页两页展示）。',
    dataFields: [
      { name: 'id', label: '发货单号', type: 'string' },
      { name: 'orderId', label: '关联订单号', type: 'string' },
      { name: 'supplier', label: '供应商', type: 'string' },
      { name: 'logisticsCompany', label: '物流公司', type: 'string' },
      { name: 'trackingNo', label: '物流运单号', type: 'string' },
      { name: 'sendTime', label: '发货时间', type: 'string' },
      { name: 'estimatedArrival', label: '预计到货时间', type: 'string' },
      { name: 'contactPhone', label: '联系电话', type: 'string' },
      { name: 'itemDesc', label: '货物描述', type: 'string' },
      { name: 'sendQty', label: '总件数', type: 'number' },
      {
        name: 'products',
        label: '货物明细',
        type: 'array',
        children: [
          { name: 'name', label: '产品/物资名称', type: 'string' },
          { name: 'spec', label: '规格型号', type: 'string' },
          { name: 'unit', label: '单位', type: 'string' },
          { name: 'quantity', label: '数量', type: 'number' },
          { name: 'price', label: '单价', type: 'currency' },
          { name: 'amount', label: '金额', type: 'currency' },
        ],
      },
    ],
    mockData: {
      id: 'DEL-20260605001',
      orderId: 'ORD-20260520092',
      supplier: '国药控股股份有限公司',
      logisticsCompany: '顺丰医药冷链',
      trackingNo: 'SF1428579632',
      sendTime: '2026-06-05 10:00:00',
      estimatedArrival: '2026-06-06',
      contactPhone: '13800138000',
      itemDesc: '冷链药品及一次性使用无菌注射器一批',
      sendQty: 1066,
      // 增加至 24 条明细，确保 A4 纸自然分页至 2 页
      products: [
        {
          name: '一次性使用无菌注射器',
          spec: '2ml',
          unit: '支',
          quantity: 300,
          price: 1.5,
          amount: 450,
        },
        {
          name: '生理盐水注射液',
          spec: '250ml',
          unit: '瓶',
          quantity: 150,
          price: 5.0,
          amount: 750,
        },
        {
          name: '葡萄糖注射液 5%',
          spec: '500ml',
          unit: '瓶',
          quantity: 100,
          price: 6.0,
          amount: 600,
        },
        {
          name: '医用防护口罩',
          spec: 'N95双挂耳',
          unit: '个',
          quantity: 200,
          price: 2.5,
          amount: 500,
        },
        {
          name: '无菌医用棉签',
          spec: '双头 50支/包',
          unit: '包',
          quantity: 50,
          price: 3.0,
          amount: 150,
        },
        {
          name: '一次性使用无菌输液器',
          spec: '带针 0.7',
          unit: '支',
          quantity: 100,
          price: 4.8,
          amount: 480,
        },
        {
          name: '医用橡胶检查手套',
          spec: 'M码 7.5',
          unit: '双',
          quantity: 50,
          price: 1.2,
          amount: 60,
        },
        {
          name: '碘伏消毒液',
          spec: '500ml/瓶',
          unit: '瓶',
          quantity: 20,
          price: 12.0,
          amount: 240,
        },
        {
          name: '免洗手消毒凝胶',
          spec: '500ml/瓶',
          unit: '瓶',
          quantity: 30,
          price: 18.0,
          amount: 540,
        },
        {
          name: '医用酒精 75%',
          spec: '500ml/瓶',
          unit: '瓶',
          quantity: 40,
          price: 6.0,
          amount: 240,
        },
        {
          name: '一次性无菌敷贴',
          spec: '10cm * 10cm',
          unit: '片',
          quantity: 20,
          price: 1.8,
          amount: 36,
        },
        {
          name: '弹性绷带',
          spec: '7.5cm * 450cm',
          unit: '卷',
          quantity: 6,
          price: 3.5,
          amount: 21,
        },
        {
          name: '脱脂纱布块',
          spec: '8cm * 10cm-12层',
          unit: '包',
          quantity: 10,
          price: 4.5,
          amount: 45,
        },
        {
          name: '退热贴',
          spec: '5cm * 12cm',
          unit: '盒',
          quantity: 5,
          price: 15.0,
          amount: 75,
        },
        {
          name: '留置针敷贴',
          spec: '6cm * 7cm',
          unit: '片',
          quantity: 20,
          price: 2.2,
          amount: 44,
        },
        {
          name: '真空采血管 (促凝)',
          spec: '红头 5ml',
          unit: '支',
          quantity: 20,
          price: 0.8,
          amount: 16,
        },
        {
          name: '一次性采血针',
          spec: '分体式 0.7',
          unit: '支',
          quantity: 10,
          price: 1.1,
          amount: 11,
        },
        {
          name: '医用纸胶带',
          spec: '2.5cm * 910cm',
          unit: '卷',
          quantity: 5,
          price: 2.5,
          amount: 12.5,
        },
        {
          name: '一次性检查垫单',
          spec: '60cm * 90cm',
          unit: '张',
          quantity: 10,
          price: 1.5,
          amount: 15,
        },
        {
          name: '一次性使用压脉带',
          spec: '乳胶',
          unit: '条',
          quantity: 5,
          price: 0.8,
          amount: 4,
        },
        // --- 跨页线 (第 2 页开始) ---
        {
          name: '一次性使用胃管',
          spec: 'Fr16',
          unit: '支',
          quantity: 3,
          price: 8.5,
          amount: 25.5,
        },
        {
          name: '一次性导尿管',
          spec: 'Fr14 双腔',
          unit: '支',
          quantity: 4,
          price: 12.5,
          amount: 50,
        },
        {
          name: '酸性氧化电位水',
          spec: '1000ml/瓶',
          unit: '瓶',
          quantity: 4,
          price: 28.0,
          amount: 112,
        },
        {
          name: '一次性医用中单',
          spec: '80cm * 150cm',
          unit: '张',
          quantity: 4,
          price: 3.2,
          amount: 12.8,
        },
      ],
    },
    fallbackPageSettings: defaultPageSettings,
    fallbackBands: [
      {
        id: 'header',
        name: '页头',
        type: 'header',
        top: 0,
        bottom: 192,
        actualBottom: 192,
        visible: true,
        objects: [
          {
            id: 'h_title',
            type: 'text',
            x: 20,
            y: 10,
            width: 500,
            height: 28,
            content: '物资发货随货同行单 (随货同行)',
            fontSize: 18,
            fontWeight: 'bold',
            textAlign: 'left',
          },
          {
            id: 'h_sub',
            type: 'text',
            x: 20,
            y: 38,
            width: 500,
            height: 16,
            content: '请收料员在收货时使用手持PDA扫描右侧二维码签收出库',
            fontSize: 11,
            color: '#8c8c8c',
          },
          {
            id: 'h_line1',
            type: 'line',
            x: 20,
            y: 48,
            width: 680,
            height: 2,
            x1: 0,
            y1: 0,
            x2: 680,
            y2: 0,
            strokeWidth: 1.5,
          },

          {
            id: 'h_lbl_id',
            type: 'text',
            x: 20,
            y: 55,
            width: 70,
            height: 20,
            content: '发货单号：',
            fontWeight: 'bold',
          },
          {
            id: 'h_val_id',
            type: 'field',
            x: 90,
            y: 55,
            width: 160,
            height: 20,
            fieldName: 'id',
          },

          {
            id: 'h_lbl_orderId',
            type: 'text',
            x: 260,
            y: 55,
            width: 70,
            height: 20,
            content: '关联订单：',
            fontWeight: 'bold',
          },
          {
            id: 'h_val_orderId',
            type: 'field',
            x: 330,
            y: 55,
            width: 160,
            height: 20,
            fieldName: 'orderId',
          },

          {
            id: 'h_lbl_supplier',
            type: 'text',
            x: 20,
            y: 80,
            width: 70,
            height: 20,
            content: '供 应 商：',
            fontWeight: 'bold',
          },
          {
            id: 'h_val_supplier',
            type: 'field',
            x: 90,
            y: 80,
            width: 400,
            height: 20,
            fieldName: 'supplier',
          },

          {
            id: 'h_lbl_carrier',
            type: 'text',
            x: 20,
            y: 105,
            width: 70,
            height: 20,
            content: '物流公司：',
            fontWeight: 'bold',
          },
          {
            id: 'h_val_carrier',
            type: 'field',
            x: 90,
            y: 105,
            width: 160,
            height: 20,
            fieldName: 'logisticsCompany',
          },

          {
            id: 'h_lbl_track',
            type: 'text',
            x: 260,
            y: 105,
            width: 70,
            height: 20,
            content: '运 单 号：',
            fontWeight: 'bold',
          },
          {
            id: 'h_val_track',
            type: 'field',
            x: 330,
            y: 105,
            width: 160,
            height: 20,
            fieldName: 'trackingNo',
          },

          {
            id: 'h_lbl_time',
            type: 'text',
            x: 20,
            y: 130,
            width: 70,
            height: 20,
            content: '发货时间：',
            fontWeight: 'bold',
          },
          {
            id: 'h_val_time',
            type: 'field',
            x: 90,
            y: 130,
            width: 160,
            height: 20,
            fieldName: 'sendTime',
          },

          {
            id: 'h_lbl_phone',
            type: 'text',
            x: 260,
            y: 130,
            width: 70,
            height: 20,
            content: '联系电话：',
            fontWeight: 'bold',
          },
          {
            id: 'h_val_phone',
            type: 'field',
            x: 330,
            y: 130,
            width: 160,
            height: 20,
            fieldName: 'contactPhone',
          },

          {
            id: 'h_qrcode',
            type: 'qrcode',
            x: 550,
            y: 10,
            width: 110,
            height: 110,
            fieldName: 'id',
          },

          {
            id: 'h_line2',
            type: 'line',
            x: 20,
            y: 160,
            width: 680,
            height: 2,
            x1: 0,
            y1: 0,
            x2: 680,
            y2: 0,
            strokeWidth: 1,
          },

          {
            id: 'th_name',
            type: 'text',
            x: 30,
            y: 165,
            width: 220,
            height: 20,
            content: '产品/物资名称',
            fontWeight: 'bold',
          },
          {
            id: 'th_spec',
            type: 'text',
            x: 260,
            y: 165,
            width: 100,
            height: 20,
            content: '规格型号',
            fontWeight: 'bold',
          },
          {
            id: 'th_unit',
            type: 'text',
            x: 370,
            y: 165,
            width: 50,
            height: 20,
            content: '单位',
            fontWeight: 'bold',
          },
          {
            id: 'th_qty',
            type: 'text',
            x: 430,
            y: 165,
            width: 70,
            height: 20,
            content: '发货数量',
            fontWeight: 'bold',
            textAlign: 'right',
          },
          {
            id: 'th_price',
            type: 'text',
            x: 510,
            y: 165,
            width: 80,
            height: 20,
            content: '单价',
            fontWeight: 'bold',
            textAlign: 'right',
          },
          {
            id: 'th_amt',
            type: 'text',
            x: 600,
            y: 165,
            width: 90,
            height: 20,
            content: '金额小计',
            fontWeight: 'bold',
            textAlign: 'right',
          },

          {
            id: 'h_line3',
            type: 'line',
            x: 20,
            y: 190,
            width: 680,
            height: 2,
            x1: 0,
            y1: 0,
            x2: 680,
            y2: 0,
            strokeWidth: 1.5,
          },
        ],
      },
      {
        id: 'detail',
        name: '明细',
        type: 'detail',
        top: 192,
        bottom: 232,
        actualBottom: 232,
        visible: true,
        objects: [
          {
            id: 'td_name',
            type: 'field',
            x: 30,
            y: 10,
            width: 220,
            height: 20,
            fieldName: 'products.name',
          },
          {
            id: 'td_spec',
            type: 'field',
            x: 260,
            y: 10,
            width: 100,
            height: 20,
            fieldName: 'products.spec',
          },
          {
            id: 'td_unit',
            type: 'field',
            x: 370,
            y: 10,
            width: 50,
            height: 20,
            fieldName: 'products.unit',
          },
          {
            id: 'td_qty',
            type: 'field',
            x: 430,
            y: 10,
            width: 70,
            height: 20,
            fieldName: 'products.quantity',
            textAlign: 'right',
          },
          {
            id: 'td_price',
            type: 'field',
            x: 510,
            y: 10,
            width: 80,
            height: 20,
            fieldName: 'products.price',
            textAlign: 'right',
          },
          {
            id: 'td_amt',
            type: 'field',
            x: 600,
            y: 10,
            width: 90,
            height: 20,
            fieldName: 'products.amount',
            textAlign: 'right',
          },
          {
            id: 'd_line',
            type: 'line',
            x: 20,
            y: 35,
            width: 680,
            height: 2,
            x1: 0,
            y1: 0,
            x2: 680,
            y2: 0,
            strokeWidth: 0.5,
            lineStyle: 'dashed',
          },
        ],
      },
      {
        id: 'summary',
        name: '汇总',
        type: 'summary',
        top: 232,
        bottom: 282,
        actualBottom: 282,
        visible: true,
        objects: [
          {
            id: 's_lbl_qty',
            type: 'text',
            x: 430,
            y: 15,
            width: 80,
            height: 20,
            content: '发货总数：',
            fontWeight: 'bold',
          },
          {
            id: 's_val_qty',
            type: 'field',
            x: 510,
            y: 15,
            width: 80,
            height: 20,
            fieldName: 'sendQty',
            textAlign: 'right',
          },
          {
            id: 's_line1',
            type: 'line',
            x: 20,
            y: 45,
            width: 680,
            height: 2,
            x1: 0,
            y1: 0,
            x2: 680,
            y2: 0,
            strokeWidth: 1.5,
          },
        ],
      },
      {
        id: 'footer',
        name: '页脚',
        type: 'footer',
        top: 282,
        bottom: 322,
        actualBottom: 322,
        visible: true,
        objects: [
          {
            id: 'f_page',
            type: 'page_number',
            x: 20,
            y: 10,
            width: 680,
            height: 20,
            format: '第 {page} 页 / 共 {pages} 页',
            textAlign: 'center',
            fontSize: 10,
            color: '#8c8c8c',
          },
        ],
      },
    ],
  },
  {
    key: 'c_purchase_order',
    name: '物资采购订单模板',
    code: 'c_purchase_order',
    description:
      '用于医院向供应商发起商品物资采购流程时的采购合同/订单打印（跨页两页展示，带双签章栏）。',
    dataFields: [
      { name: 'id', label: '采购单号', type: 'string' },
      { name: 'supplier', label: '供应商名称', type: 'string' },
      { name: 'dept', label: '采购科室', type: 'string' },
      { name: 'buyer', label: '采购员', type: 'string' },
      { name: 'phone', label: '联系电话', type: 'string' },
      { name: 'time', label: '采购时间', type: 'string' },
      { name: 'totalAmount', label: '总金额', type: 'currency' },
      {
        name: 'products',
        label: '物资明细',
        type: 'array',
        children: [
          { name: 'name', label: '物资名称', type: 'string' },
          { name: 'spec', label: '规格型号', type: 'string' },
          { name: 'quantity', label: '采购数量', type: 'number' },
          { name: 'price', label: '单价', type: 'currency' },
          { name: 'amount', label: '金额小计', type: 'currency' },
        ],
      },
    ],
    mockData: {
      id: 'ORD-20260520092',
      supplier: '国药控股股份有限公司',
      dept: '设备科耗材仓库',
      buyer: '刘采购',
      phone: '021-88889999',
      time: '2026-05-20 14:30:00',
      totalAmount: 98720.0,
      // 增加明细至 24 条以形成两页
      products: [
        {
          name: '一次性精密输液器',
          spec: '带针 0.5',
          quantity: 2000,
          price: 5.5,
          amount: 11000,
        },
        {
          name: '医用无菌敷贴',
          spec: '10cm * 10cm',
          quantity: 5000,
          price: 1.2,
          amount: 6000,
        },
        {
          name: '高分子夹板',
          spec: '7.5cm * 90cm',
          quantity: 40,
          price: 40.0,
          amount: 1600,
        },
        {
          name: '一次性使用医用口罩',
          spec: '平面挂耳',
          quantity: 10000,
          price: 0.35,
          amount: 3500,
        },
        {
          name: '橡胶外科手套',
          spec: '无菌 7.5码',
          quantity: 2000,
          price: 3.5,
          amount: 7000,
        },
        {
          name: '吸氧管',
          spec: '双鼻孔 2m',
          quantity: 500,
          price: 1.8,
          amount: 900,
        },
        {
          name: '医用高分子绷带',
          spec: '10cm * 360cm',
          quantity: 200,
          price: 15.0,
          amount: 3000,
        },
        {
          name: '医用防渗敷贴',
          spec: '6cm * 7cm',
          quantity: 1000,
          price: 2.2,
          amount: 2200,
        },
        {
          name: '气管插管',
          spec: 'ID 7.5',
          quantity: 50,
          price: 45.0,
          amount: 2250,
        },
        {
          name: '吸痰管',
          spec: 'Fr14',
          quantity: 1000,
          price: 1.5,
          amount: 1500,
        },
        {
          name: '导尿包',
          spec: '单腔 16Fr',
          quantity: 100,
          price: 35.0,
          amount: 3500,
        },
        {
          name: '负压引流袋',
          spec: '1000ml',
          quantity: 200,
          price: 8.5,
          amount: 1700,
        },
        {
          name: '麻醉面罩',
          spec: '成人中号',
          quantity: 100,
          price: 18.0,
          amount: 1800,
        },
        {
          name: '无菌缝合线',
          spec: '4-0 带针',
          quantity: 300,
          price: 12.0,
          amount: 3600,
        },
        {
          name: '医用胶带',
          spec: '2.5cm 丝绸',
          quantity: 400,
          price: 5.0,
          amount: 2000,
        },
        {
          name: '一次性电极贴',
          spec: '成人用',
          quantity: 2000,
          price: 0.8,
          amount: 1600,
        },
        {
          name: '针灸针',
          spec: '0.25 * 40mm',
          quantity: 50,
          price: 12.0,
          amount: 600,
        },
        {
          name: '一次性换药包',
          spec: '常规',
          quantity: 500,
          price: 8.5,
          amount: 4250,
        },
        {
          name: '利器盒',
          spec: '3L 圆形',
          quantity: 100,
          price: 6.5,
          amount: 650,
        },
        {
          name: '水胶体敷料',
          spec: '10cm * 10cm',
          quantity: 150,
          price: 48.0,
          amount: 7200,
        },
        // --- 跨页线 (第 2 页开始) ---
        {
          name: '抗过敏胶带',
          spec: '纸质 1.25cm',
          quantity: 500,
          price: 3.2,
          amount: 1600,
        },
        {
          name: '冲洗器',
          spec: '100ml',
          quantity: 200,
          price: 4.5,
          amount: 900,
        },
        {
          name: '压舌板',
          spec: '竹制',
          quantity: 2000,
          price: 0.15,
          amount: 300,
        },
        {
          name: '一次性中单',
          spec: '防渗 80*120',
          quantity: 1000,
          price: 2.8,
          amount: 2800,
        },
        {
          name: '外科敷料垫',
          spec: '20cm * 25cm',
          quantity: 500,
          price: 18.5,
          amount: 9250,
        },
      ],
    },
    fallbackPageSettings: defaultPageSettings,
    fallbackBands: [
      {
        id: 'header',
        name: '页头',
        type: 'header',
        top: 0,
        bottom: 175,
        actualBottom: 175,
        visible: true,
        objects: [
          {
            id: 'po_title',
            type: 'text',
            x: 20,
            y: 15,
            width: 440,
            height: 28,
            content: '医疗机构物资采购订单 (合同)',
            fontSize: 18,
            fontWeight: 'bold',
            textAlign: 'left',
          },
          {
            id: 'po_sub',
            type: 'text',
            x: 20,
            y: 42,
            width: 440,
            height: 16,
            content: '采购主体：上海第一人民医院 (SPD供应链平台自动结转)',
            fontSize: 11,
            color: '#666',
          },
          {
            id: 'po_barcode',
            type: 'barcode',
            x: 480,
            y: 10,
            width: 220,
            height: 48,
            fieldName: 'id',
          },
          {
            id: 'po_line1',
            type: 'line',
            x: 20,
            y: 60,
            width: 680,
            height: 2,
            x1: 0,
            y1: 0,
            x2: 680,
            y2: 0,
            strokeWidth: 1.5,
          },

          {
            id: 'po_lbl_id',
            type: 'text',
            x: 20,
            y: 68,
            width: 80,
            height: 20,
            content: '采购单号：',
            fontWeight: 'bold',
          },
          {
            id: 'po_val_id',
            type: 'field',
            x: 100,
            y: 68,
            width: 150,
            height: 20,
            fieldName: 'id',
          },
          {
            id: 'po_lbl_time',
            type: 'text',
            x: 420,
            y: 68,
            width: 80,
            height: 20,
            content: '采购日期：',
            fontWeight: 'bold',
          },
          {
            id: 'po_val_time',
            type: 'field',
            x: 500,
            y: 68,
            width: 200,
            height: 20,
            fieldName: 'time',
          },

          {
            id: 'po_lbl_supplier',
            type: 'text',
            x: 20,
            y: 92,
            width: 80,
            height: 20,
            content: '供 应 商：',
            fontWeight: 'bold',
          },
          {
            id: 'po_val_supplier',
            type: 'field',
            x: 100,
            y: 92,
            width: 300,
            height: 20,
            fieldName: 'supplier',
          },
          {
            id: 'po_lbl_dept',
            type: 'text',
            x: 420,
            y: 92,
            width: 80,
            height: 20,
            content: '入库科室：',
            fontWeight: 'bold',
          },
          {
            id: 'po_val_dept',
            type: 'field',
            x: 500,
            y: 92,
            width: 200,
            height: 20,
            fieldName: 'dept',
          },

          {
            id: 'po_lbl_buyer',
            type: 'text',
            x: 20,
            y: 116,
            width: 80,
            height: 20,
            content: '采 购 员：',
            fontWeight: 'bold',
          },
          {
            id: 'po_val_buyer',
            type: 'field',
            x: 100,
            y: 116,
            width: 150,
            height: 20,
            fieldName: 'buyer',
          },
          {
            id: 'po_lbl_phone',
            type: 'text',
            x: 270,
            y: 116,
            width: 80,
            height: 20,
            content: '联系电话：',
            fontWeight: 'bold',
          },
          {
            id: 'po_val_phone',
            type: 'field',
            x: 350,
            y: 116,
            width: 150,
            height: 20,
            fieldName: 'phone',
          },

          {
            id: 'po_line2',
            type: 'line',
            x: 20,
            y: 140,
            width: 680,
            height: 2,
            x1: 0,
            y1: 0,
            x2: 680,
            y2: 0,
            strokeWidth: 1,
          },

          {
            id: 'poth_name',
            type: 'text',
            x: 30,
            y: 147,
            width: 250,
            height: 20,
            content: '物资名称',
            fontWeight: 'bold',
          },
          {
            id: 'poth_spec',
            type: 'text',
            x: 290,
            y: 147,
            width: 120,
            height: 20,
            content: '规格型号',
            fontWeight: 'bold',
          },
          {
            id: 'poth_qty',
            type: 'text',
            x: 420,
            y: 147,
            width: 80,
            height: 20,
            content: '采购数量',
            fontWeight: 'bold',
            textAlign: 'right',
          },
          {
            id: 'poth_price',
            type: 'text',
            x: 510,
            y: 147,
            width: 80,
            height: 20,
            content: '单价',
            fontWeight: 'bold',
            textAlign: 'right',
          },
          {
            id: 'poth_amt',
            type: 'text',
            x: 600,
            y: 147,
            width: 90,
            height: 20,
            content: '金额小计',
            fontWeight: 'bold',
            textAlign: 'right',
          },

          {
            id: 'po_line3',
            type: 'line',
            x: 20,
            y: 172,
            width: 680,
            height: 2,
            x1: 0,
            y1: 0,
            x2: 680,
            y2: 0,
            strokeWidth: 1.5,
          },
        ],
      },
      {
        id: 'detail',
        name: '明细',
        type: 'detail',
        top: 175,
        bottom: 215,
        actualBottom: 215,
        visible: true,
        objects: [
          {
            id: 'potd_name',
            type: 'field',
            x: 30,
            y: 10,
            width: 250,
            height: 20,
            fieldName: 'products.name',
          },
          {
            id: 'potd_spec',
            type: 'field',
            x: 290,
            y: 10,
            width: 120,
            height: 20,
            fieldName: 'products.spec',
          },
          {
            id: 'potd_qty',
            type: 'field',
            x: 420,
            y: 10,
            width: 80,
            height: 20,
            fieldName: 'products.quantity',
            textAlign: 'right',
          },
          {
            id: 'potd_price',
            type: 'field',
            x: 510,
            y: 10,
            width: 80,
            height: 20,
            fieldName: 'products.price',
            textAlign: 'right',
          },
          {
            id: 'potd_amt',
            type: 'field',
            x: 600,
            y: 10,
            width: 90,
            height: 20,
            fieldName: 'products.amount',
            textAlign: 'right',
          },
          {
            id: 'po_d_line',
            type: 'line',
            x: 20,
            y: 35,
            width: 680,
            height: 2,
            x1: 0,
            y1: 0,
            x2: 680,
            y2: 0,
            strokeWidth: 0.5,
            lineStyle: 'dashed',
          },
        ],
      },
      {
        id: 'summary',
        name: '汇总',
        type: 'summary',
        top: 215,
        bottom: 350,
        actualBottom: 350,
        visible: true,
        objects: [
          {
            id: 'po_s_lbl_total',
            type: 'text',
            x: 420,
            y: 15,
            width: 90,
            height: 20,
            content: '订单总金额：',
            fontWeight: 'bold',
          },
          {
            id: 'po_s_val_total',
            type: 'field',
            x: 510,
            y: 15,
            width: 180,
            height: 20,
            fieldName: 'totalAmount',
            textAlign: 'right',
            format: 'currency',
          },

          {
            id: 'po_s_lbl_sign1',
            type: 'text',
            x: 20,
            y: 45,
            width: 200,
            height: 20,
            content: '双方确签盖章：',
            fontWeight: 'bold',
          },

          {
            id: 'po_s_lbl_sign_a',
            type: 'text',
            x: 20,
            y: 75,
            width: 300,
            height: 20,
            content: '甲方(采购方)签字：____________________',
          },
          {
            id: 'po_s_lbl_date_a',
            type: 'text',
            x: 20,
            y: 105,
            width: 200,
            height: 20,
            content: '日期：______年____月____日',
          },

          {
            id: 'po_s_lbl_sign_b',
            type: 'text',
            x: 380,
            y: 75,
            width: 300,
            height: 20,
            content: '乙方(供货方)签字：____________________',
          },
          {
            id: 'po_s_lbl_date_b',
            type: 'text',
            x: 380,
            y: 105,
            width: 200,
            height: 20,
            content: '日期：______年____月____日',
          },

          {
            id: 'po_s_line1',
            type: 'line',
            x: 20,
            y: 130,
            width: 680,
            height: 2,
            x1: 0,
            y1: 0,
            x2: 680,
            y2: 0,
            strokeWidth: 1.5,
          },
        ],
      },
      {
        id: 'footer',
        name: '页脚',
        type: 'footer',
        top: 350,
        bottom: 390,
        actualBottom: 390,
        visible: true,
        objects: [
          {
            id: 'po_f_page',
            type: 'page_number',
            x: 20,
            y: 10,
            width: 680,
            height: 20,
            format: '第 {page} 页 / 共 {pages} 页',
            textAlign: 'center',
            fontSize: 10,
            color: '#8c8c8c',
          },
        ],
      },
    ],
  },
  {
    key: 'c_dept_requisition',
    name: '科室领用单模板',
    code: 'c_dept_requisition',
    description:
      '用于医院内部科室向中心仓库领用医疗耗材/药品的出库领料记录打印（跨页两页展示，包含双联签字）。',
    dataFields: [
      { name: 'id', label: '领用单号', type: 'string' },
      { name: 'dept', label: '领用科室', type: 'string' },
      { name: 'recipient', label: '领用人', type: 'string' },
      { name: 'auditor', label: '审核人', type: 'string' },
      { name: 'time', label: '领用时间', type: 'string' },
      {
        name: 'products',
        label: '物资明细',
        type: 'array',
        children: [
          { name: 'name', label: '物资名称', type: 'string' },
          { name: 'spec', label: '规格型号', type: 'string' },
          { name: 'quantity', label: '领用数量', type: 'number' },
          { name: 'unit', label: '单位', type: 'string' },
          { name: 'usage', label: '领用用途', type: 'string' },
        ],
      },
    ],
    mockData: {
      id: 'REQ-20260601008',
      dept: '骨科病区',
      recipient: '王护士',
      auditor: '张护士长',
      time: '2026-06-01 09:15:00',
      // 增加明细至 23 条以形成两页
      products: [
        {
          name: '一次性使用医用口罩',
          spec: '耳挂式',
          quantity: 200,
          unit: '个',
          usage: '科室常规防护',
        },
        {
          name: '医用生理盐水',
          spec: '100ml',
          quantity: 50,
          unit: '袋',
          usage: '临床配药',
        },
        {
          name: '无菌棉签',
          spec: '双头 50支/包',
          quantity: 20,
          unit: '包',
          usage: '换药室备用',
        },
        {
          name: '一次性使用无菌注射器',
          spec: '5ml',
          quantity: 300,
          unit: '支',
          usage: '病区抽药用',
        },
        {
          name: '无菌输液贴',
          spec: '防水型',
          quantity: 400,
          unit: '片',
          usage: '临床输液',
        },
        {
          name: '医用棉球',
          spec: '无菌 10g',
          quantity: 50,
          unit: '包',
          usage: '换药备用',
        },
        {
          name: '绑式压脉带',
          spec: '一次性',
          quantity: 100,
          unit: '条',
          usage: '采血室备用',
        },
        {
          name: '酒精棉球',
          spec: '100粒/瓶',
          quantity: 10,
          unit: '瓶',
          usage: '皮肤消毒',
        },
        {
          name: '一次性医用中单',
          spec: '60cm * 90cm',
          quantity: 100,
          unit: '张',
          usage: '床位辅垫',
        },
        {
          name: '医用留置针',
          spec: '22G 蓝色',
          quantity: 150,
          unit: '支',
          usage: '临床静脉留置',
        },
        {
          name: '医用纸胶带',
          spec: '1.25cm',
          quantity: 30,
          unit: '卷',
          usage: '贴片固定',
        },
        {
          name: '高分子绷带',
          spec: '5cm * 270cm',
          quantity: 15,
          unit: '卷',
          usage: '骨关节外固定',
        },
        {
          name: '创口贴',
          spec: '弹性布 100片',
          quantity: 5,
          unit: '盒',
          usage: '科室备用',
        },
        {
          name: '一次性吸引管',
          spec: 'Fr14',
          quantity: 50,
          unit: '支',
          usage: '吸痰器吸头',
        },
        {
          name: '无菌包',
          spec: '门诊清创用',
          quantity: 10,
          unit: '包',
          usage: '小手术缝合',
        },
        {
          name: '医用降温贴',
          spec: '薄荷型',
          quantity: 20,
          unit: '片',
          usage: '物理降温',
        },
        {
          name: '医用凡士林纱布',
          spec: '10cm * 10cm',
          quantity: 30,
          unit: '包',
          usage: '烧伤创面覆盖',
        },
        {
          name: '弹性网状绷带',
          spec: '3号 头型',
          quantity: 10,
          unit: '条',
          usage: '头部敷贴固定',
        },
        {
          name: '医用吸水纸巾',
          spec: '抽取式',
          quantity: 50,
          unit: '包',
          usage: '手部清洁干燥',
        },
        {
          name: '一次性检查垫',
          spec: '防渗',
          quantity: 80,
          unit: '张',
          usage: '换药床辅铺',
        },
        // --- 跨页线 (第 2 页开始) ---
        {
          name: '一次性使用胃包',
          spec: '常规',
          quantity: 5,
          unit: '包',
          usage: '临床置胃管',
        },
        {
          name: '一次性使用导尿包',
          spec: '带双腔导尿管',
          quantity: 10,
          unit: '包',
          usage: '临床置尿管',
        },
        {
          name: '强效消毒洗手液',
          spec: '500ml 压泵',
          quantity: 6,
          unit: '瓶',
          usage: '科室手部卫生',
        },
      ],
    },
    fallbackPageSettings: defaultPageSettings,
    fallbackBands: [
      {
        id: 'header',
        name: '页头',
        type: 'header',
        top: 0,
        bottom: 170,
        actualBottom: 170,
        visible: true,
        objects: [
          {
            id: 'req_title',
            type: 'text',
            x: 20,
            y: 15,
            width: 400,
            height: 28,
            content: '科室耗材物料领用单',
            fontSize: 18,
            fontWeight: 'bold',
            textAlign: 'left',
          },
          {
            id: 'req_sub',
            type: 'text',
            x: 20,
            y: 42,
            width: 400,
            height: 16,
            content: '中心库房出料存根 (双联单/出库随附)',
            fontSize: 11,
            color: '#8c8c8c',
          },
          {
            id: 'req_barcode',
            type: 'barcode',
            x: 450,
            y: 10,
            width: 220,
            height: 48,
            fieldName: 'id',
          },
          {
            id: 'req_line1',
            type: 'line',
            x: 20,
            y: 60,
            width: 680,
            height: 2,
            x1: 0,
            y1: 0,
            x2: 680,
            y2: 0,
            strokeWidth: 1.5,
          },

          {
            id: 'req_lbl_id',
            type: 'text',
            x: 20,
            y: 68,
            width: 80,
            height: 20,
            content: '领用单号：',
            fontWeight: 'bold',
          },
          {
            id: 'req_val_id',
            type: 'field',
            x: 100,
            y: 68,
            width: 150,
            height: 20,
            fieldName: 'id',
          },
          {
            id: 'req_lbl_time',
            type: 'text',
            x: 420,
            y: 68,
            width: 80,
            height: 20,
            content: '领用时间：',
            fontWeight: 'bold',
          },
          {
            id: 'req_val_time',
            type: 'field',
            x: 500,
            y: 68,
            width: 200,
            height: 20,
            fieldName: 'time',
          },

          {
            id: 'req_lbl_dept',
            type: 'text',
            x: 20,
            y: 92,
            width: 80,
            height: 20,
            content: '领用科室：',
            fontWeight: 'bold',
          },
          {
            id: 'req_val_dept',
            type: 'field',
            x: 100,
            y: 92,
            width: 200,
            height: 20,
            fieldName: 'dept',
          },

          {
            id: 'req_lbl_recipient',
            type: 'text',
            x: 20,
            y: 116,
            width: 80,
            height: 20,
            content: '领 用 人：',
            fontWeight: 'bold',
          },
          {
            id: 'req_val_recipient',
            type: 'field',
            x: 100,
            y: 116,
            width: 120,
            height: 20,
            fieldName: 'recipient',
          },
          {
            id: 'req_lbl_auditor',
            type: 'text',
            x: 270,
            y: 116,
            width: 80,
            height: 20,
            content: '审 核 人：',
            fontWeight: 'bold',
          },
          {
            id: 'req_val_auditor',
            type: 'field',
            x: 350,
            y: 116,
            width: 120,
            height: 20,
            fieldName: 'auditor',
          },

          {
            id: 'req_line2',
            type: 'line',
            x: 20,
            y: 138,
            width: 680,
            height: 2,
            x1: 0,
            y1: 0,
            x2: 680,
            y2: 0,
            strokeWidth: 1,
          },

          {
            id: 'reqth_name',
            type: 'text',
            x: 30,
            y: 145,
            width: 250,
            height: 20,
            content: '物资名称',
            fontWeight: 'bold',
          },
          {
            id: 'reqth_spec',
            type: 'text',
            x: 290,
            y: 145,
            width: 120,
            height: 20,
            content: '规格型号',
            fontWeight: 'bold',
          },
          {
            id: 'reqth_qty',
            type: 'text',
            x: 420,
            y: 145,
            width: 70,
            height: 20,
            content: '领用数量',
            fontWeight: 'bold',
            textAlign: 'right',
          },
          {
            id: 'reqth_unit',
            type: 'text',
            x: 500,
            y: 145,
            width: 50,
            height: 20,
            content: '单位',
            fontWeight: 'bold',
            textAlign: 'center',
          },
          {
            id: 'reqth_usage',
            type: 'text',
            x: 560,
            y: 145,
            width: 130,
            height: 20,
            content: '领用用途',
            fontWeight: 'bold',
          },

          {
            id: 'req_line3',
            type: 'line',
            x: 20,
            y: 168,
            width: 680,
            height: 2,
            x1: 0,
            y1: 0,
            x2: 680,
            y2: 0,
            strokeWidth: 1.5,
          },
        ],
      },
      {
        id: 'detail',
        name: '明细',
        type: 'detail',
        top: 170,
        bottom: 210,
        actualBottom: 210,
        visible: true,
        objects: [
          {
            id: 'reqtd_name',
            type: 'field',
            x: 30,
            y: 10,
            width: 250,
            height: 20,
            fieldName: 'products.name',
          },
          {
            id: 'reqtd_spec',
            type: 'field',
            x: 290,
            y: 10,
            width: 120,
            height: 20,
            fieldName: 'products.spec',
          },
          {
            id: 'reqtd_qty',
            type: 'field',
            x: 420,
            y: 10,
            width: 70,
            height: 20,
            fieldName: 'products.quantity',
            textAlign: 'right',
          },
          {
            id: 'reqtd_unit',
            type: 'field',
            x: 500,
            y: 10,
            width: 50,
            height: 20,
            fieldName: 'products.unit',
            textAlign: 'center',
          },
          {
            id: 'reqtd_usage',
            type: 'field',
            x: 560,
            y: 10,
            width: 130,
            height: 20,
            fieldName: 'products.usage',
          },
          {
            id: 'req_d_line',
            type: 'line',
            x: 20,
            y: 35,
            width: 680,
            height: 2,
            x1: 0,
            y1: 0,
            x2: 680,
            y2: 0,
            strokeWidth: 0.5,
            lineStyle: 'dashed',
          },
        ],
      },
      {
        id: 'summary',
        name: '汇总',
        type: 'summary',
        top: 210,
        bottom: 290,
        actualBottom: 290,
        visible: true,
        objects: [
          {
            id: 'req_s_lbl_sign',
            type: 'text',
            x: 20,
            y: 15,
            width: 300,
            height: 20,
            content: '领用人签字：____________________',
            fontWeight: 'bold',
          },
          {
            id: 'req_s_lbl_sign2',
            type: 'text',
            x: 380,
            y: 15,
            width: 300,
            height: 20,
            content: '库管发货人签字：__________________',
            fontWeight: 'bold',
          },
          {
            id: 'req_s_lbl_sign3',
            type: 'text',
            x: 20,
            y: 45,
            width: 300,
            height: 20,
            content: '领用科室盖章：__________________',
            fontWeight: 'bold',
          },
          {
            id: 'req_s_lbl_sign4',
            type: 'text',
            x: 380,
            y: 45,
            width: 300,
            height: 20,
            content: '发料库房：中心耗材库',
            fontWeight: 'bold',
          },
          {
            id: 'req_s_line1',
            type: 'line',
            x: 20,
            y: 80,
            width: 680,
            height: 2,
            x1: 0,
            y1: 0,
            x2: 680,
            y2: 0,
            strokeWidth: 1.5,
          },
        ],
      },
      {
        id: 'footer',
        name: '页脚',
        type: 'footer',
        top: 290,
        bottom: 330,
        actualBottom: 330,
        visible: true,
        objects: [
          {
            id: 'req_f_page',
            type: 'page_number',
            x: 20,
            y: 10,
            width: 680,
            height: 20,
            format: '第 {page} 页 / 共 {pages} 页',
            textAlign: 'center',
            fontSize: 10,
            color: '#8c8c8c',
          },
        ],
      },
    ],
  },
  {
    key: 'c_finance_statement',
    name: '财务结算对账单模板',
    code: 'c_finance_statement',
    description:
      '用于医院与合作供应商之间按周期进行发票对账与结算时的确认单据（跨页两页展示，附核准签字栏）。',
    dataFields: [
      { name: 'id', label: '对账单号', type: 'string' },
      { name: 'period', label: '对账账期', type: 'string' },
      { name: 'supplier', label: '供应商', type: 'string' },
      { name: 'checker', label: '核对人', type: 'string' },
      { name: 'time', label: '结算核对时间', type: 'string' },
      { name: 'totalPayable', label: '结算应付总额', type: 'currency' },
      {
        name: 'products',
        label: '对账发票明细',
        type: 'array',
        children: [
          { name: 'invoiceNo', label: '发票号码', type: 'string' },
          { name: 'invoiceAmount', label: '发票金额', type: 'currency' },
          { name: 'orderId', label: '关联采购单', type: 'string' },
          { name: 'statusName', label: '对账核对状态', type: 'string' },
        ],
      },
    ],
    mockData: {
      id: 'FIN-20260601009',
      period: '2026年5月份账期 (05.01 - 05.31)',
      supplier: '国药控股股份有限公司',
      checker: '周财务',
      time: '2026-06-01 16:00:00',
      totalPayable: 978000.0,
      // 增加明细至 23 条以形成两页
      products: [
        {
          invoiceNo: 'INV-20260515001',
          invoiceAmount: 45000,
          orderId: 'ORD-2026051201',
          statusName: '核对一致，已付',
        },
        {
          invoiceNo: 'INV-20260520023',
          invoiceAmount: 55000,
          orderId: 'ORD-2026051802',
          statusName: '核对一致，待付',
        },
        {
          invoiceNo: 'INV-20260528092',
          invoiceAmount: 18000,
          orderId: 'ORD-2026052511',
          statusName: '核对一致，已付',
        },
        {
          invoiceNo: 'INV-20260528093',
          invoiceAmount: 22000,
          orderId: 'ORD-2026052512',
          statusName: '核对一致，已付',
        },
        {
          invoiceNo: 'INV-20260529012',
          invoiceAmount: 34000,
          orderId: 'ORD-2026052602',
          statusName: '核对一致，已付',
        },
        {
          invoiceNo: 'INV-20260529013',
          invoiceAmount: 67000,
          orderId: 'ORD-2026052605',
          statusName: '核对一致，待付',
        },
        {
          invoiceNo: 'INV-20260530045',
          invoiceAmount: 12000,
          orderId: 'ORD-2026052701',
          statusName: '核对一致，已付',
        },
        {
          invoiceNo: 'INV-20260530046',
          invoiceAmount: 89000,
          orderId: 'ORD-2026052702',
          statusName: '核对一致，待付',
        },
        {
          invoiceNo: 'INV-20260530047',
          invoiceAmount: 45000,
          orderId: 'ORD-2026052703',
          statusName: '核对一致，已付',
        },
        {
          invoiceNo: 'INV-20260530048',
          invoiceAmount: 23000,
          orderId: 'ORD-2026052704',
          statusName: '核对一致，已付',
        },
        {
          invoiceNo: 'INV-20260531001',
          invoiceAmount: 90000,
          orderId: 'ORD-2026052801',
          statusName: '核对一致，已付',
        },
        {
          invoiceNo: 'INV-20260531002',
          invoiceAmount: 15000,
          orderId: 'ORD-2026052802',
          statusName: '核对一致，已付',
        },
        {
          invoiceNo: 'INV-20260531003',
          invoiceAmount: 76000,
          orderId: 'ORD-2026052803',
          statusName: '核对一致，待付',
        },
        {
          invoiceNo: 'INV-20260531004',
          invoiceAmount: 32000,
          orderId: 'ORD-2026052804',
          statusName: '核对一致，已付',
        },
        {
          invoiceNo: 'INV-20260531005',
          invoiceAmount: 65000,
          orderId: 'ORD-2026052805',
          statusName: '核对一致，已付',
        },
        {
          invoiceNo: 'INV-20260531006',
          invoiceAmount: 28000,
          orderId: 'ORD-2026052806',
          statusName: '核对一致，已付',
        },
        {
          invoiceNo: 'INV-20260531007',
          invoiceAmount: 43000,
          orderId: 'ORD-2026052807',
          statusName: '核对一致，待付',
        },
        {
          invoiceNo: 'INV-20260531008',
          invoiceAmount: 56000,
          orderId: 'ORD-2026052808',
          statusName: '核对一致，已付',
        },
        {
          invoiceNo: 'INV-20260531009',
          invoiceAmount: 11000,
          orderId: 'ORD-2026052809',
          statusName: '核对一致，已付',
        },
        {
          invoiceNo: 'INV-20260531010',
          invoiceAmount: 73000,
          orderId: 'ORD-2026052810',
          statusName: '核对一致，已付',
        },
        // --- 跨页线 (第 2 页开始) ---
        {
          invoiceNo: 'INV-20260531011',
          invoiceAmount: 28000,
          orderId: 'ORD-2026052811',
          statusName: '核对一致，待付',
        },
        {
          invoiceNo: 'INV-20260531012',
          invoiceAmount: 48000,
          orderId: 'ORD-2026052812',
          statusName: '核对一致，已付',
        },
        {
          invoiceNo: 'INV-20260531013',
          invoiceAmount: 34000,
          orderId: 'ORD-2026052813',
          statusName: '核对一致，已付',
        },
      ],
    },
    fallbackPageSettings: defaultPageSettings,
    fallbackBands: [
      {
        id: 'header',
        name: '页头',
        type: 'header',
        top: 0,
        bottom: 170,
        actualBottom: 170,
        visible: true,
        objects: [
          {
            id: 'fin_title',
            type: 'text',
            x: 20,
            y: 15,
            width: 500,
            height: 28,
            content: '供应链结算对账审核确认单',
            fontSize: 18,
            fontWeight: 'bold',
            textAlign: 'left',
          },
          {
            id: 'fin_sub',
            type: 'text',
            x: 20,
            y: 42,
            width: 500,
            height: 16,
            content: '财务结算专用联 (双方核对开票相符后生效)',
            fontSize: 11,
            color: '#8c8c8c',
          },
          {
            id: 'fin_qrcode',
            type: 'qrcode',
            x: 550,
            y: 10,
            width: 100,
            height: 100,
            fieldName: 'id',
          },
          {
            id: 'fin_line1',
            type: 'line',
            x: 20,
            y: 50,
            width: 680,
            height: 2,
            x1: 0,
            y1: 0,
            x2: 680,
            y2: 0,
            strokeWidth: 1.5,
          },

          {
            id: 'fin_lbl_id',
            type: 'text',
            x: 20,
            y: 58,
            width: 80,
            height: 20,
            content: '对账单号：',
            fontWeight: 'bold',
          },
          {
            id: 'fin_val_id',
            type: 'field',
            x: 100,
            y: 58,
            width: 150,
            height: 20,
            fieldName: 'id',
          },
          {
            id: 'fin_lbl_time',
            type: 'text',
            x: 270,
            y: 58,
            width: 80,
            height: 20,
            content: '确认时间：',
            fontWeight: 'bold',
          },
          {
            id: 'fin_val_time',
            type: 'field',
            x: 350,
            y: 58,
            width: 180,
            height: 20,
            fieldName: 'time',
          },

          {
            id: 'fin_lbl_supplier',
            type: 'text',
            x: 20,
            y: 82,
            width: 80,
            height: 20,
            content: '合作客商：',
            fontWeight: 'bold',
          },
          {
            id: 'fin_val_supplier',
            type: 'field',
            x: 100,
            y: 82,
            width: 300,
            height: 20,
            fieldName: 'supplier',
          },
          {
            id: 'fin_lbl_period',
            type: 'text',
            x: 270,
            y: 82,
            width: 80,
            height: 20,
            content: '对账账期：',
            fontWeight: 'bold',
          },
          {
            id: 'fin_val_period',
            type: 'field',
            x: 350,
            y: 82,
            width: 180,
            height: 20,
            fieldName: 'period',
          },

          {
            id: 'fin_lbl_checker',
            type: 'text',
            x: 20,
            y: 106,
            width: 80,
            height: 20,
            content: '财务核对：',
            fontWeight: 'bold',
          },
          {
            id: 'fin_val_checker',
            type: 'field',
            x: 100,
            y: 106,
            width: 150,
            height: 20,
            fieldName: 'checker',
          },

          {
            id: 'fin_line2',
            type: 'line',
            x: 20,
            y: 135,
            width: 680,
            height: 2,
            x1: 0,
            y1: 0,
            x2: 680,
            y2: 0,
            strokeWidth: 1,
          },

          {
            id: 'finth_inv',
            type: 'text',
            x: 30,
            y: 142,
            width: 200,
            height: 20,
            content: '发票号码',
            fontWeight: 'bold',
          },
          {
            id: 'finth_amt',
            type: 'text',
            x: 250,
            y: 142,
            width: 130,
            height: 20,
            content: '发票开具金额',
            fontWeight: 'bold',
            textAlign: 'right',
          },
          {
            id: 'finth_order',
            type: 'text',
            x: 400,
            y: 142,
            width: 150,
            height: 20,
            content: '关联采购单号',
            fontWeight: 'bold',
          },
          {
            id: 'finth_status',
            type: 'text',
            x: 570,
            y: 142,
            width: 120,
            height: 20,
            content: '核对审核状态',
            fontWeight: 'bold',
            textAlign: 'center',
          },

          {
            id: 'fin_line3',
            type: 'line',
            x: 20,
            y: 168,
            width: 680,
            height: 2,
            x1: 0,
            y1: 0,
            x2: 680,
            y2: 0,
            strokeWidth: 1.5,
          },
        ],
      },
      {
        id: 'detail',
        name: '明细',
        type: 'detail',
        top: 170,
        bottom: 210,
        actualBottom: 210,
        visible: true,
        objects: [
          {
            id: 'fintd_inv',
            type: 'field',
            x: 30,
            y: 10,
            width: 200,
            height: 20,
            fieldName: 'products.invoiceNo',
          },
          {
            id: 'fintd_amt',
            type: 'field',
            x: 250,
            y: 10,
            width: 130,
            height: 20,
            fieldName: 'products.invoiceAmount',
            textAlign: 'right',
            format: 'currency',
          },
          {
            id: 'fintd_order',
            type: 'field',
            x: 400,
            y: 10,
            width: 150,
            height: 20,
            fieldName: 'products.orderId',
          },
          {
            id: 'fintd_status',
            type: 'field',
            x: 570,
            y: 10,
            width: 120,
            height: 20,
            fieldName: 'products.statusName',
            textAlign: 'center',
          },
          {
            id: 'fin_d_line',
            type: 'line',
            x: 20,
            y: 35,
            width: 680,
            height: 2,
            x1: 0,
            y1: 0,
            x2: 680,
            y2: 0,
            strokeWidth: 0.5,
            lineStyle: 'dashed',
          },
        ],
      },
      {
        id: 'summary',
        name: '汇总',
        type: 'summary',
        top: 210,
        bottom: 340,
        actualBottom: 340,
        visible: true,
        objects: [
          {
            id: 'fin_s_lbl',
            type: 'text',
            x: 380,
            y: 15,
            width: 130,
            height: 20,
            content: '结算应付总额：',
            fontWeight: 'bold',
          },
          {
            id: 'fin_s_val',
            type: 'field',
            x: 510,
            y: 15,
            width: 180,
            height: 20,
            fieldName: 'totalPayable',
            textAlign: 'right',
            format: 'currency',
          },

          {
            id: 'fin_s_desc',
            type: 'text',
            x: 20,
            y: 45,
            width: 660,
            height: 20,
            content:
              '声明：本期往来账项开具的发票经双方核实无误，同意进入医院结算付款流程。',
            fontSize: 11,
            color: '#666',
          },

          {
            id: 'fin_s_sign_a',
            type: 'text',
            x: 20,
            y: 75,
            width: 300,
            height: 20,
            content: '医院财务审批人(签字)：_________________',
          },
          {
            id: 'fin_s_date_a',
            type: 'text',
            x: 20,
            y: 105,
            width: 200,
            height: 20,
            content: '日期：______年____月____日',
          },

          {
            id: 'fin_s_sign_b',
            type: 'text',
            x: 380,
            y: 75,
            width: 300,
            height: 20,
            content: '客商财务负责人(签字)：_________________',
          },
          {
            id: 'fin_s_date_b',
            type: 'text',
            x: 380,
            y: 105,
            width: 200,
            height: 20,
            content: '日期：______年____月____日',
          },

          {
            id: 'fin_s_line1',
            type: 'line',
            x: 20,
            y: 130,
            width: 680,
            height: 2,
            x1: 0,
            y1: 0,
            x2: 680,
            y2: 0,
            strokeWidth: 1.5,
          },
        ],
      },
      {
        id: 'footer',
        name: '页脚',
        type: 'footer',
        top: 340,
        bottom: 380,
        actualBottom: 380,
        visible: true,
        objects: [
          {
            id: 'fin_f_page',
            type: 'page_number',
            x: 20,
            y: 10,
            width: 680,
            height: 20,
            format: '第 {page} 页 / 共 {pages} 页',
            textAlign: 'center',
            fontSize: 10,
            color: '#8c8c8c',
          },
        ],
      },
    ],
  },
];
