import { defineMock } from '@umijs/max';

export default defineMock({
  'GET /api/procurement/contracts': (req: any, res: any) => {
    const { status, domain, keyword, current = 1, pageSize = 10 } = req.query;

    const allContracts = [
      {
        id: 'CT-2025-006',
        name: '2025年度医用耗材供货框架协议',
        type: 'annual',
        typeName: '年度框架',
        supplier: '浙江振德医疗用品有限公司',
        supplierCode: 'S-VD-001',
        domain: 'consumable',
        signDate: '2025-01-10',
        startDate: '2025-01-01',
        endDate: '2025-12-31',
        totalAmount: 2800000,
        executedAmount: 860000,
        status: 'active',
        statusName: '生效中',
        contactPerson: '陈思远',
        contactPhone: '0571-88998899',
        remark: '覆盖口罩、手套、手术衣等三大类日常耗材，设有价格调节条款',
      },
      {
        id: 'CT-2025-015',
        name: '2025年度一次性医疗器械供货协议',
        type: 'annual',
        typeName: '年度框架',
        supplier: '上海医疗器械股份有限公司',
        supplierCode: 'S-SH-002',
        domain: 'consumable',
        signDate: '2025-01-15',
        startDate: '2025-01-01',
        endDate: '2025-12-31',
        totalAmount: 1560000,
        executedAmount: 420000,
        status: 'active',
        statusName: '生效中',
        contactPerson: '吴晓燕',
        contactPhone: '021-64389900',
        remark: '乳胶手套、棉签、绷带等耗品供货',
      },
      {
        id: 'CT-2025-018',
        name: '骨科手术耗材战略供货协议',
        type: 'annual',
        typeName: '年度框架',
        supplier: '北京中科医疗器械有限公司',
        supplierCode: 'S-BJ-003',
        domain: 'consumable',
        signDate: '2025-02-01',
        startDate: '2025-02-01',
        endDate: '2026-01-31',
        totalAmount: 5200000,
        executedAmount: 1250000,
        status: 'active',
        statusName: '生效中',
        contactPerson: '刘志远',
        contactPhone: '010-88886666',
        remark: '注射器、输液器等通用耗材，含年度价格调整机制',
      },
      {
        id: 'CT-2025-019',
        name: '2025年精密输液器采购合同',
        type: 'single',
        typeName: '单次采购',
        supplier: '百特（中国）投资有限公司',
        supplierCode: 'S-BX-004',
        domain: 'consumable',
        signDate: '2025-03-10',
        startDate: '2025-03-10',
        endDate: '2025-09-10',
        totalAmount: 380000,
        executedAmount: 268000,
        status: 'active',
        statusName: '生效中',
        contactPerson: '方云鹏',
        contactPhone: '010-65789900',
        remark: '精密输液器、三通阀等专项合同',
      },
      {
        id: 'CT-2025-022',
        name: '2025年度西药供货框架合同',
        type: 'annual',
        typeName: '年度框架',
        supplier: '国药控股广州有限公司',
        supplierCode: 'S-GD-005',
        domain: 'medicine',
        signDate: '2024-12-20',
        startDate: '2025-01-01',
        endDate: '2025-12-31',
        totalAmount: 8500000,
        executedAmount: 3200000,
        status: 'active',
        statusName: '生效中',
        contactPerson: '黄建平',
        contactPhone: '020-82228888',
        remark: '全院基本药品及常规用药供货，国控战略合作协议',
      },
      {
        id: 'CT-2025-028',
        name: '麻醉及特殊管理药品供货合同',
        type: 'annual',
        typeName: '年度框架',
        supplier: '扬子江药业集团有限公司',
        supplierCode: 'S-YZ-006',
        domain: 'medicine',
        signDate: '2025-01-05',
        startDate: '2025-01-01',
        endDate: '2025-12-31',
        totalAmount: 1200000,
        executedAmount: 480000,
        status: 'active',
        statusName: '生效中',
        contactPerson: '李敏',
        contactPhone: '0511-85679000',
        remark: '丙泊酚、舒芬太尼等麻醉药品，实行双人双锁管控',
      },
      {
        id: 'CT-2025-031',
        name: '骨科高值植入物战略合作合同',
        type: 'annual',
        typeName: '年度框架',
        supplier: '强生（上海）医疗器材有限公司',
        supplierCode: 'S-JJ-007',
        domain: 'consumable',
        signDate: '2025-01-20',
        startDate: '2025-01-01',
        endDate: '2025-12-31',
        totalAmount: 12000000,
        executedAmount: 3850000,
        status: 'active',
        statusName: '生效中',
        contactPerson: '王丽萍',
        contactPhone: '021-63891234',
        remark: '钛合金锁定骨板、髋关节置换系统等高值植入物',
      },
      {
        id: 'CT-2024-055',
        name: '2024年造影剂采购合同',
        type: 'annual',
        typeName: '年度框架',
        supplier: '通用电气医疗系统贸易发展（上海）有限公司',
        supplierCode: 'S-GE-008',
        domain: 'medicine',
        signDate: '2024-01-05',
        startDate: '2024-01-01',
        endDate: '2024-12-31',
        totalAmount: 2100000,
        executedAmount: 2100000,
        status: 'expired',
        statusName: '已到期',
        contactPerson: '钱国庆',
        contactPhone: '021-32298800',
        remark: '2024年度已执行完毕，2025年已切换至碧迪医疗',
      },
    ];

    let filtered = allContracts;
    if (domain) filtered = filtered.filter((c) => c.domain === domain);
    if (status) filtered = filtered.filter((c) => c.status === status);
    if (keyword) {
      filtered = filtered.filter(
        (c) =>
          c.id.includes(keyword) ||
          c.name.includes(keyword) ||
          c.supplier.includes(keyword),
      );
    }

    const start = (Number(current) - 1) * Number(pageSize);
    const data = filtered.slice(start, start + Number(pageSize));

    res.json({ data, total: filtered.length, success: true });
  },
});
